### ISSUE TITLE
Attempt to call an undefined function glGenerateMipmap

### ISSUE THREAD

**Issue by hfgukd** [mcedit/mcedit2#10]
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:262]:Using accelerated ArrayDatatype
[INFO][mceditlib.blocktypes:187]:Loading block info from (215266) <open file 'C:\\Users\\TonyHTan\\AppData\\Local\\Temp\\_MEI58362\\mceditlib\\blocktypes\\minecraft_raw.json', mode 'r' at 0x0000000006A7A780>
[INFO][mceditlib.blocktypes:187]:Loading block info from (8112) <open file 'C:\\Users\\TonyHTan\\AppData\\Local\\Temp\\_MEI58362\\mceditlib\\blocktypes\\minecraft.json', mode 'r' at 0x0000000006A7A780>
[INFO][mcedit2.util.profiler:86]:Decorating <function __iter__ at 0x0000000006CB93C8> with SectionUpdate
[INFO][mcedit2.util.profiler:86]:Decorating <function workOnChunk at 0x0000000007C36208> with SlicedMesh
[WARNING][mcedit2.editorapp:76]:UserFilesDirectory: C:\Users\TonyHTan\Desktop\MCEDIT~2\MCEdit User Data
[INFO][mcedit2.worldlist:177]:Scanning C:\Users\TonyHTan\AppData\Roaming\.minecraft\saves for worlds...
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.-2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-2.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-2.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.-2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.3.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.3.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.2.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.2.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.2.2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58593.58593.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58593.58594.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58594.58593.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58594.58594.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.0.mca
[INFO][mcedit2.editorapp:256]:Loading timer started
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.-2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-2.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-2.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.-2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.3.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.1.3.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.2.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.2.1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.2.2.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58593.58593.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58593.58594.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58594.58593.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.58594.58594.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.-1.0.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.-1.mca
[INFO][mceditlib.anvil.worldfolder:120]:Unexpected file in region folder: ._r.0.0.mca
[INFO][mcedit2.util.scanmodules:14]:Scanning mcedit2.rendering.blockmeshes (C:\Users\TonyHTan\AppData\Local\Temp\_MEI58362\mcedit2\rendering\blockmeshes\__init__.pyc)
[WARNING][mcedit2.rendering.blockmeshes:123]:Unregistered renderers: 
  BrewingStand,  TripWire,  Log,  Anvil,  EndPortalFrame,  Lever,  DragonEgg,  Quartz,  Repeater,  Fire,  Stem,  Beacon,  Comparator,  Crops,  Flowerpot,  Bed,  MinecartTrack,  LilyPad,  Door,  PistonBase,  TripWireSource,  RedstoneLogic,  Wall,  Hopper,  Cauldron,  Cocoa,  FenceGate,  Pane,  PistonExtension,  Cactus
[INFO][mcedit2.rendering.textureatlas:114]:Preloaded 213 textures for world lmaoidk (515 kB)
[INFO][mcedit2.rendering.chunkloader:112]:Added: client MinimapWorldView(u'lmaoidk')
[INFO][mcedit2.worldlist:244]:Centering on single-player player.
[INFO][mcedit2.worldlist:260]:Switched world view
[INFO][mcedit2.rendering.loadablechunks:90]:Making checkerboard texture...
[INFO][mceditlib.worldeditor:307]:Scanning for regions in C:\Users\TonyHTan\AppData\Roaming\.minecraft\saves\lmaoidk...
[INFO][mceditlib.worldeditor:317]:Dim : Found 16003 chunks in 0.42 seconds.
[INFO][mceditlib.worldeditor:317]:Dim DIM1: Found 1313 chunks in 0.05 seconds.
[INFO][mceditlib.worldeditor:317]:Dim DIM-1: Found 2764 chunks in 0.11 seconds.
[INFO][OpenGL.extensions:92]:OpenGL Version: 2.1.0 - Build 8.15.10.1851
[INFO][OpenGL.extensions:148]:GL Extension GL_ARB_framebuffer_object unavailable
[ERROR][mcedit2.main:135]:Unhandled Exception: 
	Attempt to call an undefined function glGenerateMipmap, check for bool(glGenerateMipmap) before calling
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.worldview", line 386, in paintGL (self is a MinimapWorldView)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 377, in renderScene  
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a MatrixRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a DepthOffsetRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 122, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.textureatlas", line 195, in load (self is a TextureAtlas)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 226, in load (self is a Texture)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\OpenGL.platform.baseplatform", line 384, in __call__  
NullFunctionError: Attempt to call an undefined function glGenerateMipmap, check for bool(glGenerateMipmap) before calling
[ERROR][mcedit2.main:135]:Unhandled Exception: 
	'TextureAtlas' object has no attribute 'width'
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.worldview", line 386, in paintGL (self is a MinimapWorldView)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 377, in renderScene  
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a MatrixRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a DepthOffsetRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 123, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 80, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 105, in draw (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 135, in enter (self is a TextureAtlasRenderNode)
AttributeError: 'TextureAtlas' object has no attribute 'width'

**Comment by codewarrior0** [comment]
Fixed
