### ISSUE TITLE
Entry Point Not Found error on startup

### ISSUE THREAD

**Issue by llVIU** [mcedit/mcedit2#107]
http://s23.postimg.org/zbjaknhhn/screenshot_27.png

alpha432

**Comment by codewarrior0** [comment]
Related to https://github.com/zeromq/pyzmq/issues/521

**Comment by codewarrior0** [comment]
I will try to build the next version using the official `pyzmq` files instead of Chris Gohlke's.

For now, the current builds are not compatible with Windows XP.

**Comment by mcpebro** [comment]
[INFO][<string>:131]:MCEdit2 version 2.0.0alpha-435 starting...
[INFO][mcedit2.util.profiler:87]:Decorating <function work at 0x02DF01B0> with work
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:270]:Using accelerated ArrayDatatype
[INFO][mcedit2.util.profiler:87]:Decorating <function loadSections at 0x03412670> with SelectionScene
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0345A470> with ChunkUpdate
[INFO][mcedit2.util.profiler:87]:Decorating <function buildChunkMeshes at 0x0345A430> with buildChunkMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function buildSectionMeshes at 0x0345A4F0> with buildSectionMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0345AD30> with SectionUpdate
[INFO][mcedit2.util.settings:100]:Loading app settings from C:\DOCUME~1\owner\Desktop\mcedit\MCEDIT~2.0AL\MCEdit User Data\mcedit2.ini
[INFO][mcedit2.util.profiler:87]:Decorating <function workOnChunk at 0x037313F0> with SlicedMesh
[ERROR][<string>:153]:Unhandled Exception: 
	[Error 127] The specified procedure could not be found
Traceback (most recent call last):
  File "<string>", line 171, in <module>  
  File "<string>", line 167, in main  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.profiler", line 65, in _wrapper (self is a Profiler)
  File "<string>", line 142, in startup  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.editorapp", line 33, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.ipython_widget", line 67, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.qt.inprocess", line 5, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.kernel", line 4, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.kernel.zmq", line 14, in <module>  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.utils.zmqrelated", line 35, in check_for_zmq  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\zmq", line 30, in <module>  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\ctypes", line 443, in LoadLibrary (self is a LibraryLoader)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\ctypes", line 365, in __init__ (self is a CDLL)
WindowsError: [Error 127] The specified procedure could not be found

**Comment by llVIU** [comment]
is there anything I can help with, like a log or something, or a version that you want me to test?

Also, I had an old version, MCEdit-0.1.7.1.win32, and apparently it works just fine with the latest minecraft version. If it wasn't for MCEdit, I would've never even bothered to play minecraft

**Comment by codewarrior0** [comment]
I think I know what's causing it. I just haven't gotten around to updating my build system yet.

If you can, verify that the crash only happens on Windows XP and not a newer version of Windows.
