### ISSUE TITLE
Does not detect OpenGL version accurately

### ISSUE THREAD

**Issue by iJunkie22** [mcedit/mcedit2#116]
I got this ***very*** interesting result:
> Obtained a GL context with this format:
> Valid: True
> Version: 1.0
> Hardware Accelerated: True
> Depth buffer: True, 24
> Double buffer: True
> 
> Driver info:
> GL_VERSION: 2.1 INTEL-10.6.8 ***(0, 0)***
> GL_VENDOR: Intel Inc.
> GL_RENDERER: Intel HD Graphics 5000 OpenGL Engine

@codewarrior0

**Comment by codewarrior0** [comment]
If you run mcedit2 with the `-debug` option, do you get a crash?

**Comment by iJunkie22** [comment]
No, but only because it exits.
> (ENV)Ethans-MacBook-Air:mcedit2 ethan$ mcedit2 -debug
> Logging level set
> Logging to /Users/ethan/Developer/PycharmProjects/mcedit2/MCEdit User Data/mcedit.log
> Setting up console handler
> usage: mcedit2 [-h] [-resetPrefs RESETPREFS] [-eval EVAL]
>                [filename [filename ...]]
> mcedit2: error: unrecognized arguments: -debug

**Comment by codewarrior0** [comment]
Oh right, that broke after I added "Enable Developer Mode" to the Options menu.

Instead of that, go to `main.py:47` and delete these two lines:

```
if "-debug" not in sys.argv:
    OpenGL.ERROR_CHECKING = False
```

Then run `mcedit2` again.

**Comment by iJunkie22** [comment]
```
[ERROR][main.py:150]:Unhandled Exception: 
	GLError(
	err = 1280,
	description = 'invalid enumerant',
	baseOperation = glGetIntegerv,
	pyArgs = (
		GL_MAJOR_VERSION,
		<object object at 0x1018e28d0>,
	),
	cArgs = (
		GL_MAJOR_VERSION,
		array([0], dtype=int32, shape=(1,)),
	),
	cArguments = (
		GL_MAJOR_VERSION,
		array([0], dtype=int32, shape=(1,)),
	)
)
Traceback (most recent call last):
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/ENV/bin/mcedit2", line 9, in <module>  
    load_entry_point('mcedit2==2.0.0a1.dev0', 'console_scripts', 'mcedit2')()
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/main.py", line 164, in main  
    app = startup()
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/util/profiler.py", line 65, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/main.py", line 141, in startup  
    editorApp = MCEditApp(sys.argv)
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/editorapp.py", line 257, in __init__ (self is a MCEditApp)
    self.worldList = WorldListWidget(mainWindow)
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/worldlist.py", line 243, in __init__ (self is a WorldListWidget)
    self.reloadList()
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/worldlist.py", line 337, in reloadList (self is a WorldListWidget)
    self.showWorld(self.worldListModel.worlds[0][0])
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/worldlist.py", line 376, in showWorld (self is a WorldListWidget)
    self.setWorldView(MinimapWorldView(dim, textureAtlas))
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/worldview/minimap.py", line 148, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/worldview/worldview.py", line 93, in __init__ (self is a MinimapWorldView)
    validateQGLContext(self.context())
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/src/mcedit2/util/qglcontext.py", line 44, in validateQGLContext  
    major = GL.glGetInteger(GL.GL_MAJOR_VERSION)
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/ENV/lib/python2.7/site-packages/OpenGL/latebind.py", line 45, in __call__ (self is a glGetIntegerv)
    return self._finalCall( *args, **named )
  File "/Users/ethan/Developer/PycharmProjects/mcedit2/ENV/lib/python2.7/site-packages/OpenGL/wrapper.py", line 664, in wrapperCall (self is a glGetIntegerv)
    raise err
GLError: GLError(
	err = 1280,
	description = 'invalid enumerant',
	baseOperation = glGetIntegerv,
	pyArgs = (
		GL_MAJOR_VERSION,
		<object object at 0x1018e28d0>,
	),
	cArgs = (
		GL_MAJOR_VERSION,
		array([0], dtype=int32, shape=(1,)),
	),
	cArguments = (
		GL_MAJOR_VERSION,
		array([0], dtype=int32, shape=(1,)),
	)
)
```

**Comment by codewarrior0** [comment]
Just as I expected. Why do Intel drivers have to be so... special? Fine, I'll parse `GL_VERSION` instead.
