### ISSUE TITLE
Broken world

### ISSUE THREAD

**Issue by ejcole7** [mcedit/mcedit2#12]
My world on minecraft (after using mc edit on it) keeps making my minecraft crash! Here is the error

[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[17:08:51] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[17:08:51] [Server thread/WARN]: Wrong location! EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3243, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3244, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3245, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3246, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3247, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3248, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3249, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3250, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3251, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3252, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3253, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3254, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3255, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3256, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3257, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3258, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3259, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3260, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3261, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3262, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3263, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3264, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3265, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3266, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3267, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3268, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3269, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3270, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3271, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3272, l='survive poop', x=183.05, y=66.25, z=38.44] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3273, l='survive poop', x=185.66, y=67.17, z=38.37] (at 11, 2 instead of 10, 1)
EntityVillagerAdult['entity.mca.EntityVillagerAdult.name'/3274, l='survive poop', x=172.76, y=62.00, z=50.30] (at 10, 3 instead of 10, 1)

**Comment by codewarrior0** [comment]
[Read the Reporting Guidelines](https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md) again and update your issue with the required information.

https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
