### ISSUE TITLE
When a map is opened, clicking on "2D" crashes mcedit

### ISSUE THREAD

**Issue by tyronx** [mcedit/mcedit2#148]
An error has occured.
Unhandled exception: 'CutawayWorldView' object has no attribute 'cameraVector'

Logs:
[ERROR][<string>:153]:Unhandled Exception: 
	'CutawayWorldView' object has no attribute 'cameraVector'
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.editorsession", line 1105, in viewOffsetChanged (self is a EditorTab)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.minimap", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
AttributeError: 'CutawayWorldView' object has no attribute 'cameraVector'

**Comment by codewarrior0** [comment]
Fixed.

**Comment by vcid** [comment]
This same thing is happening for me, is the fixed version yet to be released?

**Comment by codewarrior0** [comment]
2D view is broken in other ways. Don't hold your breath for a release.
