### ISSUE TITLE
TypeError: Cannot cast dtype('float64') to dtype('uint8')

### ISSUE THREAD

**Issue by Podshot** [mcedit/mcedit2#155]
Python Version: 2.7.5 64-bit (because many other programs require that specific version)
MCEdit2 Version number: Latest Source
Minecraft Version: Happens before even loading a world (1.8 anyway)
OS: Windows 8.1 64-bit
Steps to reproduce: Just open up MCEdit
Error Log (from the console): 
```
[ERROR][chunkupdate.py:194]:Failed rendering for mesh class <class 'mcedit2.rendering.chunkmeshes.lowdetail.OverheadBlockMesh'>: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
Traceback (most recent call last):
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\rendering\chunkupdate.py", line 191, in buildChunkMeshes (self is a ChunkUpdate)
    for _ in profiler.iterate(worker, name):
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\util\profiler.py", line 80, in iterate (self is a Profiler)
    val = it.next()
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\rendering\chunkmeshes\lowdetail.py", line 128, in makeChunkVertices (self is a OverheadBlockMesh)
    flatcolors *= 0.8
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind
```
With NumPy version 1.9.2-mkl (from Gohlke's download page), MCEdit2 won't run, and with NumPy 1.10-mkl (also from Gohlke) the error will constantly spam the console. Haven't tested with your custom builds, but I'll only do that if the error cannot be fixed another way.

**Comment by codewarrior0** [comment]
Can't reproduce:

```
$ pip install ~/Downloads/numpy-1.9.2+mkl-cp27-none-win_amd64.whl
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Processing c:\users\rio\downloads\numpy-1.9.2+mkl-cp27-none-win_amd64.whl
Installing collected packages: numpy
Successfully installed numpy-1.9.2
(ENV64)
Rio@RIO-PC ~/Documents/mcedit2-distrib/mcedit2 (master)
$ ipython
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy

In [2]: a=numpy.arange(10, dtype='uint8')

In [3]: a *= 0.8

In [4]: a
Out[4]: array([0, 0, 1, 2, 3, 4, 4, 5, 6, 7], dtype=uint8)
```

Are you using a virtualenv?

**Comment by codewarrior0** [comment]
>With NumPy version 1.9.2-mkl (from Gohlke's download page), MCEdit2 won't run

Why?

**Comment by Podshot** [comment]
I am using virtualenv. Here is the error when running with 1.9.2-mkl:
```
[ERROR][main.py:186]:Unhandled Exception: 
	numpy.dtype has the wrong size, try recompiling
Traceback (most recent call last):
  File "C:\Users\<user>\Python\MCEdit2\MCEdit2\src\mcedit2\main.py", line 204, in <module>  
    main()
  File "C:\Users\<user>\Python\MCEdit2\MCEdit2\src\mcedit2\main.py", line 200, in main  
    app = startup()
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\util\profiler.py", line 66, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "C:\Users\<user>\Python\MCEdit2\MCEdit2\src\mcedit2\main.py", line 175, in startup  
    from mcedit2.editorapp import MCEditApp
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\editorapp.py", line 13, in <module>  
    from mcedit2 import plugins
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\plugins.py", line 12, in <module>  
    from mcedit2.editortools import generate
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\editortools\generate.py", line 15, in <module>  
    from mcedit2.rendering.worldscene import WorldScene
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\rendering\worldscene.py", line 14, in <module>  
    from mcedit2.rendering import chunkupdate
  File "c:\users\<user>\python\mcedit2\mcedit2\src\mcedit2\rendering\chunkupdate.py", line 8, in <module>  
    from mcedit2.rendering.modelmesh import BlockModelMesh
  File "ENV\lib\site-packages\Cython\Includes\numpy\__init__.pxd", line 155, in init mcedit2.rendering.modelmesh (src/mcedit2/rendering/modelmesh.c:25456)  
    ctypedef class numpy.dtype [object PyArray_Descr]:
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by codewarrior0** [comment]
`pip install -U cython`?

**Comment by Podshot** [comment]
Pip says it is up to date

**Comment by codewarrior0** [comment]
Sounds like you didn't rebuild after changing numpy versions. Try `python setup.py build_ext -i --force`.

**Comment by Podshot** [comment]
Yep that fixed it, thanks!
