### ISSUE TITLE
Move Error

### ISSUE THREAD

**Issue by FrznFlms** [mcedit/mcedit2#159]
Any time I try to move something, it gives me this error:
MCEdit version: 2.0.0alpha-720
Python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-10.0.10240
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 355.60 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 650/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.editortools.move", line 326, in confirmImport (self is a MoveTool)
  File "out00-PYZ.pyz\mcedit2.util.showprogress", line 45, in showProgress  
  File "out00-PYZ.pyz\mceditlib.util.progress", line 26, in rescaleProgress  
  File "out00-PYZ.pyz\mceditlib.block_copy", line 225, in copyBlocksIter  
ZeroDivisionError: float division by zero

If you attempt to restart MCEdit using the option on the error window, it also gives this error.

**Comment by codewarrior0** [comment]
Fixed in 0815f61b767ffad46d5f4f6962e681abfcc3a253
