### ISSUE TITLE
Can't recover minecraft classic .dat level

### ISSUE THREAD

**Issue by DelvarWorld** [mcedit/mcedit2#166]
Crash:

	MCEdit version: 2.0.0alpha-823
	Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
	Platform: win32
	System version: Windows-7-6.1.7601-SP1
	Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

	Obtained a GL context with this format:
	Valid: True
	Version: 4.5
	Hardware Accelerated: True
	Depth buffer: True, 24
	Double buffer: True

	Driver info:
	GL_VERSION: 4.5.0 NVIDIA 347.52 (4, 5)
	GL_VENDOR: 'NVIDIA Corporation'
	GL_RENDERER: 'GeForce GTX 960/PCIe/SSE2'

	------

	Unhandled Exception

	Traceback (most recent call last):
	  File "out00-PYZ.pyz\mcedit2.worldlist", line 311, in openWorldClicked (self is a WorldListWidget)
	  File "out00-PYZ.pyz\mcedit2.editorapp", line 780, in chooseOpenWorld (self is a MCEditApp)
	  File "out00-PYZ.pyz\mcedit2.editorapp", line 698, in loadFile (self is a MCEditApp)
	  File "out00-PYZ.pyz\mcedit2.editorsession", line 148, in __init__ (self is a EditorSession)
	  File "out00-PYZ.pyz\mceditlib.worldeditor", line 226, in __init__ (self is a WorldEditor)
	  File "out00-PYZ.pyz\mceditlib.findadapter", line 62, in findAdapter  
	ValueError: Cannot detect type of file C:/server_level.dat.

**Comment by codewarrior0** [comment]
Support for classic levels is not even planned at this time. Use MCEdit 0.1.7.1 to convert the classic level by importing it into a modern level.

**Comment by DelvarWorld** [comment]
I don't see that version on http://khroki.github.io/MCEdit-Unified/ ?
