### ISSUE TITLE
Exception upon using brush tool

### ISSUE THREAD

**Issue by MalzM** [mcedit/mcedit2#167]
The version was built from the github files yesterday (29.10.15)
The error occures upon using the brush in a loaded map.

----

MCEdit version: HOMEBAKED
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 358.50 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 670/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "d:\programme\mcedit 2.0\src\mcedit2\command.py", line 27, in redo (self is a BrushCommand)
    self.perform()
  File "d:\programme\mcedit 2.0\src\mcedit2\editortools\brush\__init__.py", line 70, in perform (self is a BrushCommand)
    exhaust(self._perform())
  File "d:\programme\mcedit 2.0\src\mceditlib\util\__init__.py", line 29, in exhaust  
    for i in _iter:
  File "d:\programme\mcedit 2.0\src\mcedit2\editortools\brush\__init__.py", line 79, in _perform (self is a BrushCommand)
    self.brushMode.applyToSelections(self, selections)
  File "d:\programme\mcedit 2.0\src\mcedit2\editortools\brush\modes.py", line 102, in applyToSelections (self is a Fill)
    showProgress("Applying brush...", fill)
  File "d:\programme\mcedit 2.0\src\mcedit2\util\showprogress.py", line 77, in showProgress  
    for progress in task:
  File "d:\programme\mcedit 2.0\src\mceditlib\util\progress.py", line 26, in rescaleProgress  
    for progress in iterable:
  File "d:\programme\mcedit 2.0\src\mceditlib\operations\__init__.py", line 36, in next (self is a FillBlocksOperation)
    self.operateOnChunk(chunk)
  File "d:\programme\mcedit 2.0\src\mceditlib\operations\block_fill.py", line 143, in operateOnChunk (self is a FillBlocksOperation)
    mceditlib.relight.updateLightsByCoord(self.dimension, x, y, z)
  File "src\mceditlib\relight\with_cython.pyx", line 397, in mceditlib.relight.with_cython.updateLightsByCoord (src/mceditlib/relight/with_cython.cpp:5521)  
    x = np.asarray(x, 'i32').ravel()
  File "D:\Programme\MCEdit 2.0\ENV\lib\site-packages\numpy\core\numeric.py", line 474, in asarray  
    return array(a, dtype, copy=False, order=order)
TypeError: data type "i32" not understood

**Comment by codewarrior0** [comment]
MCEdit is not updated for NumPy 1.10 at the moment. Try it with Numpy 1.9 instead. You may need to rerun MCEdit's setup.py with --force to rebuild cython modules that use Numpy.

**Comment by MalzM** [comment]
Alright, gonna give it a try. Sorry for my fault!

**Comment by MalzM** [comment]
Sorry, took a while cause I wasn't at home! But the issue is solved, thanks!
