### ISSUE TITLE
Issue to export schematics

### ISSUE THREAD

**Issue by thealejandroxv** [mcedit/mcedit2#168]
MCEdit version: 2.0.0alpha-823
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-post2012Server-6.3.9600
Processor: Intel64 Family 6 Model 26 Stepping 5, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 358.87 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 760/PCIe/SSE2'

Unhandled Exception

Traceback (most recent call last):
File "out00-PYZ.pyz\mcedit2.editorsession", line 825, in export (self is a EditorSession)
File "out00-PYZ.pyz\mceditlib.worldeditor", line 805, in exportSchematicIter (self is a WorldEditorDimension)
File "out00-PYZ.pyz\mceditlib.schematic", line 45, in createSchematic

File "out00-PYZ.pyz\mceditlib.schematic", line 210, in init (self is a SchematicFileAdapter)
ValueError: negative dimensions are not allowed

**Comment by codewarrior0** [comment]
Steps to reproduce?

**Comment by thealejandroxv** [comment]
1. Select a Big zone with XZY numbers
2. Export

**Comment by codewarrior0** [comment]
Not a startup error. Make sure your numbers are ordered correctly when you select by XYZ numbers.

https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
