### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by PolarClad** [mcedit/mcedit2#172]
MCEdit version: 2.0.0alpha-816
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10.0.10240
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.3.0 - Build 10.18.15.4256 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4400'

------

Unhandled Exception

Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.editorsession", line 825, in export (self is a EditorSession)
  File "out00-PYZ.pyz\mceditlib.worldeditor", line 805, in exportSchematicIter (self is a WorldEditorDimension)
  File "out00-PYZ.pyz\mceditlib.schematic", line 33, in createSchematic  
  File "out00-PYZ.pyz\mceditlib.schematic", line 211, in __init__ (self is a SchematicFileAdapter)
MemoryError

**Comment by codewarrior0** [comment]
Not a startup error.

https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
