### ISSUE TITLE
Crashing After Confirming Schematic

### ISSUE THREAD

**Issue by Khippie** [mcedit/mcedit2#174]
I was using MCEdit 2.0.0alpha907 and when I tried to import a schematic and save it, it came up with:

MCEdit version: 2.0.0alpha-907
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.3.12618 Compatibility Profile Context 13.251.9001.1001 (4, 3)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon HD 7700 Series'

Unhandled Exception

Traceback (most recent call last):
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editortools\move.py", line 241, in confirmImport (self is a MoveTool)
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\util\showprogress.py", line 77, in showProgress

File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\util\progress.py", line 26, in rescaleProgress

File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\block_copy.py", line 222, in copyBlocksIter

File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entities.py", line 304, in copyWithOffset (self is a PCTileEntityRefBase)
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\nbtattr.py", line 330, in set (self is a KeyedVectorAttr)
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entities.py", line 319, in dirty (self is a PCTileEntityRefBase)
AttributeError: 'NoneType' object has no attribute 'dirty'

**Comment by codewarrior0** [comment]
Not a startup error.

https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
