### ISSUE TITLE
Error when i exported schematic

### ISSUE THREAD

**Issue by oliverthecute** [mcedit/mcedit2#175]
I was using MCEdit 2.0.0alpha907 and when I tried to export a schematic and save it, it came up with:
MCEdit version: 2.0.0alpha-907
Python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: AMD64 Family 21 Model 48 Stepping 1, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.13399 Compatibility Profile Context 15.201.1151.0 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon R7 Series + R7 240 Dual Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mcedit2\editorsession.py", line 898, in export (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mcedit2\util\showprogress.py", line 77, in showProgress  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mceditlib\util\progress.py", line 26, in rescaleProgress  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mceditlib\block_copy.py", line 222, in copyBlocksIter  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mceditlib\anvil\entities.py", line 304, in copyWithOffset (self is a PCTileEntityRefBase)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mceditlib\nbtattr.py", line 330, in __set__ (self is a KeyedVectorAttr)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\src\mceditlib\anvil\entities.py", line 319, in dirty (self is a PCTileEntityRefBase)
AttributeError: 'NoneType' object has no attribute 'dirty'

**Comment by codewarrior0** [comment]
Not a startup error.

https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
