### ISSUE TITLE
i need help with tis bug for mcedit 2.0.0alpha-907 PLEASE HELP ME AS SOON AS YOU SEE THIS {BUG}

### ISSUE THREAD

**Issue by WolvesUnited** [mcedit/mcedit2#177]
MCEdit version: 2.0.0alpha-907
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 55 Stepping 8, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.0.0 - Build 10.18.10.3408 (4, 0)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editortools\move.py", line 241, in confirmImport (self is a MoveTool)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\util\showprogress.py", line 77, in showProgress  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\util\progress.py", line 26, in rescaleProgress  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\block_copy.py", line 215, in copyBlocksIter  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entities.py", line 214, in copyWithOffset (self is a PCEntityRefBase)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\nbtattr.py", line 260, in __set__ (self is a NBTVectorAttr)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entities.py", line 224, in dirty (self is a PCEntityRefBase)
AttributeError: 'NoneType' object has no attribute 'dirty'

**Comment by WolvesUnited** [comment]
PLEASE HELP ME ANY ONE

**Comment by WolvesUnited** [comment]
PLEASE HELP ME ANY ONE

**Comment by WolvesUnited** [comment]
BY THE WAY ITS NOT c:\Users\Rio\ ITS c:\Users\WolvesUnited/

**Comment by WolvesUnited** [comment]
any advice can help me

**Comment by WolvesUnited** [comment]
PLEASE :(

**Comment by codewarrior0** [comment]
Already fixed.

**Comment by WolvesUnited** [comment]
FIXED???

**Comment by WolvesUnited** [comment]
HOW DO I MAKE TI WORK THANKS FOR CHATING TO MAKE THINGS WORK OUT FOR ME
