### ISSUE TITLE
Accress Write Errors

### ISSUE THREAD

**Issue by AlTucker** [mcedit/mcedit2#18]
I have loved all of your previous versions of this software and have long awaited the latest that would handle all the new blocks in Minecraft.

I down loaded the software onto my win7 64bit machine and after about 3 seconds it crashes.

Here is a copy of my the log file....

[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:262]:Using accelerated ArrayDatatype
[INFO][mceditlib.blocktypes:187]:Loading block info from (215266) <open file 'C:\\Users\\ALBERT~1\\AppData\\Local\\Temp\\_MEI24962\\mceditlib\\blocktypes\\minecraft_raw.json', mode 'r' at 0x0000000006A5F780>
[INFO][mceditlib.blocktypes:187]:Loading block info from (8112) <open file 'C:\\Users\\ALBERT~1\\AppData\\Local\\Temp\\_MEI24962\\mceditlib\\blocktypes\\minecraft.json', mode 'r' at 0x0000000006A5F780>
[INFO][mcedit2.util.profiler:86]:Decorating <function __iter__ at 0x0000000006DB4358> with SectionUpdate
[INFO][mcedit2.util.profiler:86]:Decorating <function workOnChunk at 0x0000000007C85198> with SlicedMesh
[WARNING][mcedit2.editorapp:76]:UserFilesDirectory: D:\ALBERT~1\desktop\MCEdit2\MCEDIT~1\MCEdit User Data
[INFO][mcedit2.worldlist:177]:Scanning C:\Users\Albert-Dell-PC\AppData\Roaming\.minecraft\saves for worlds...
[INFO][mcedit2.editorapp:256]:Loading timer started
[INFO][mcedit2.util.scanmodules:14]:Scanning mcedit2.rendering.blockmeshes (C:\Users\ALBERT~1\AppData\Local\Temp\_MEI24962\mcedit2\rendering\blockmeshes\__init__.pyc)
[WARNING][mcedit2.rendering.blockmeshes:123]:Unregistered renderers: 
  BrewingStand,  TripWire,  Log,  Anvil,  EndPortalFrame,  Lever,  DragonEgg,  Quartz,  Repeater,  Fire,  Stem,  Beacon,  Comparator,  Crops,  Flowerpot,  Bed,  MinecartTrack,  LilyPad,  Door,  PistonBase,  TripWireSource,  RedstoneLogic,  Wall,  Hopper,  Cauldron,  Cocoa,  FenceGate,  Pane,  PistonExtension,  Cactus
[INFO][mcedit2.rendering.textureatlas:114]:Preloaded 213 textures for world World (515 kB)
[INFO][mcedit2.rendering.chunkloader:112]:Added: client MinimapWorldView(u'World')
[INFO][mcedit2.worldlist:244]:Centering on single-player player.
[INFO][mcedit2.worldlist:260]:Switched world view
[INFO][mcedit2.rendering.loadablechunks:90]:Making checkerboard texture...
[INFO][mceditlib.worldeditor:307]:Scanning for regions in C:\Users\Albert-Dell-PC\AppData\Roaming\.minecraft\saves\World...
[INFO][mceditlib.worldeditor:317]:Dim : Found 214404 chunks in 2.29 seconds.
[INFO][OpenGL.extensions:92]:OpenGL Version: 3.1.0 - Build 9.17.10.3040
[INFO][OpenGL.extensions:148]:GL Extension GL_ARB_framebuffer_object available
[ERROR][mcedit2.main:135]:Unhandled Exception: 
	exception: access violation writing 0xFFFFFFFFEAD5F450
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.worldview", line 386, in paintGL (self is a MinimapWorldView)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 377, in renderScene  
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a MatrixRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 77, in compile (self is a DepthOffsetRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 122, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.textureatlas", line 195, in load (self is a TextureAtlas)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 226, in load (self is a Texture)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\OpenGL.platform.baseplatform", line 379, in __call__ (self is a glGenerateMipmap)
WindowsError: exception: access violation writing 0xFFFFFFFFEAD5F450
[ERROR][mcedit2.main:135]:Unhandled Exception:

**Comment by agusztin** [comment]
I have the same error
http://i.gyazo.com/8fbd4f06af198c059e2575db90d7b663.png
mcedit.log http://pastebin.com/NdKX7rML

**Comment by codewarrior0** [comment]
Already fixed.
