### ISSUE TITLE
PLEASE HELP ME AS SOON AS YOU SEE THIS CODE BUG FOR MC EDIT 2.0.0ALPHA-907

### ISSUE THREAD

**Issue by WolvesUnited** [mcedit/mcedit2#181]
MCEdit version: 2.0.0alpha-907
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 55 Stepping 8, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.0.0 - Build 10.18.10.3408 (4, 0)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editortools\move.py", line 241, in confirmImport (self is a MoveTool)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\util\showprogress.py", line 77, in showProgress  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\util\progress.py", line 26, in rescaleProgress  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\block_copy.py", line 222, in copyBlocksIter  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entities.py", line 304, in copyWithOffset (self is a PCTileEntityRefBase)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\nbtattr.py", line 330, in __set__ (self is a KeyedVectorAttr)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entities.py", line 319, in dirty (self is a PCTileEntityRefBase)
AttributeError: 'NoneType' object has no attribute 'dirty'

**Comment by rockydog92** [comment]
Dude, I’m just browsing though my emails trying o tell it to add this sender and it’s domain to my safe senders list but it wont work (DARN YOU WINDOWS LIVE MAIL 2012!!!!)  
But I looked at this email and I saw this...
            System version: Windows-8-629200
                                                      ^
Look Right Here-----------------------|  
Your using Windows 8, not even 8.1 just 8.   Upgrade to Windows 8.1 or Windows 10.  Then maybe it will work.

From: WolvesUnited 
Sent: Sunday, December 13, 2015 6:45 PM
To: mcedit/mcedit2 
Subject: [mcedit2] PLEASE HELP ME AS SOON AS YOU SEE THIS CODE BUG FOR MC EDIT 2.0.0ALPHA-907 (#181)

MCEdit version: 200alpha-907
Python version: 279 (default, Dec 10 2014, 12:28:03) [MSC v1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-629200
Processor: Intel64 Family 6 Model 55 Stepping 8, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 40
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 400 - Build 1018103408 (4, 0)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics'


--------------------------------------------------------------------------------

Unhandled Exception

Traceback (most recent call last):
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editortools\movepy", line 241, in confirmImport (self is a MoveTool)
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\util\showprogresspy", line 77, in showProgress

File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\util\progresspy", line 26, in rescaleProgress

File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\block_copypy", line 222, in copyBlocksIter

File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entitiespy", line 304, in copyWithOffset (self is a PCTileEntityRefBase)
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\nbtattrpy", line 330, in set (self is a KeyedVectorAttr)
File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mceditlib\anvil\entitiespy", line 319, in dirty (self is a PCTileEntityRefBase)
AttributeError: 'NoneType' object has no attribute 'dirty'
