### ISSUE TITLE
i cant copy or export (no mods 1.8.8)

### ISSUE THREAD

**Issue by taifu6139** [mcedit/mcedit2#184]
when i try to copy or export my sky island it stops with an error message, i tried to export a small piece of dirt off of the ground and that worked, additionally i was able to clone the island i made sure there were no broken blocks but i'm not sure, this is what the error message said.

MCEdit version: 2.0.0alpha-918
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 353.82 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 680/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 900, in export (self is a EditorSession)
  File "mcedit2\util\showprogress.py", line 77, in showProgress  
  File "mceditlib\util\progress.py", line 26, in rescaleProgress  
  File "mceditlib\block_copy.py", line 222, in copyBlocksIter  
  File "mceditlib\anvil\entities.py", line 304, in copyWithOffset (self is a PCTileEntityChestRef)
  File "mceditlib\nbtattr.py", line 330, in __set__ (self is a KeyedVectorAttr)
  File "mceditlib\anvil\entities.py", line 319, in dirty (self is a PCTileEntityChestRef)
AttributeError: 'NoneType' object has no attribute 'dirty'

**Comment by codewarrior0** [comment]
Fixed.

**Comment by taifu6139** [comment]
so i should just reinstall or?

**Comment by codewarrior0** [comment]
Download the next build when it comes out. Builds are posted at 10:00 UTC.

**Comment by taifu6139** [comment]
ok perfect, thank you for getting back to me so quickly

**Comment by alteveer** [comment]
Which change fixes this?
