### ISSUE TITLE
Modded Minecraft and Unhandled exceptions

### ISSUE THREAD

**Issue by ArlinDel** [mcedit/mcedit2#185]
I am tryiing to fix an agrarian skies 2 map that keeps crashing my server.
 But I keep getting this error when trying to load into the world

```
MCEdit version: 2.0.0alpha-907
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 358.50 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 660/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorapp.py", line 747, in editWorldFromList (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorapp.py", line 698, in loadFile (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 362, in __init__ (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 670, in setConfiguredBlocks (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 674, in reloadModels (self is a EditorSession)
  File "mcedit2\rendering\blockmodels.pyx", line 233, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:5092)  
    self.loadModel(block, resourcePath, resourceVariant, modelDict, variantXrot, variantYrot)
  File "mcedit2\rendering\blockmodels.pyx", line 320, in mcedit2.rendering.blockmodels.BlockModels.loadModel (src/mcedit2/rendering/blockmodels.c:6499)  
    modelDict = self._getBlockModel(parentName)
  File "mcedit2\rendering\blockmodels.pyx", line 116, in mcedit2.rendering.blockmodels.BlockModels._getBlockModel (src/mcedit2/rendering/blockmodels.c:3075)  
    return self._getBlockModelByPath(modelPath)
  File "mcedit2\rendering\blockmodels.pyx", line 121, in mcedit2.rendering.blockmodels.BlockModels._getBlockModelByPath (src/mcedit2/rendering/blockmodels.c:3236)  
    model = json.load(self.resourceLoader.openStream(modelPath))
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\resourceloader.py", line 55, in openStream (self is a ResourceLoader)
ResourceNotFound: u'Resource assets/minecraft/models/block/cube_all.json not found in search path'
```

**Comment by codewarrior0** [comment]
Fixed
