### ISSUE TITLE
Mcedit2 crash on start Win 10 Pro

### ISSUE THREAD

**Issue by taniz123456789** [mcedit/mcedit2#186]
I'm using mcedit2-win64-2.0.0alpha-918 on Windows 10 pro

System info
Processor: AMD FX 6300
Ram: 8 GB
system type: 64-bit Windows 10 Pro
Graphics card: Nvidia Gtx 960
 
Error details:
MCEdit version: 2.0.0alpha-918
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 359.00 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 960/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

I open mcedit2.exe loads up then crashes when the GUI loads with the error above.
I'm using minecraft 1.8.9

**Comment by pakarr** [comment]
same here for me
MCEdit version: 2.0.0alpha-918
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.3.0 - Build 10.18.15.4248 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4600'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

looks like everything's the same except for our hardware.

**Comment by patrikfors** [comment]
Same here as well, looks like DisplayList.compile failed or never was called..

MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.3.0 - Build 10.18.15.4248 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4400'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

**Comment by codewarrior0** [comment]
Fixed in 3ad11dc0c7619ac067995c0896ef76d72ebbf0c0
