### ISSUE TITLE
MCEDIT 2.0.0aplha-919 will not open

### ISSUE THREAD

**Issue by Matty3672** [mcedit/mcedit2#193]
Open and get the following message. On restart it will not load and clicking "continue" just reloads the same message
Minecraft version - 1.8.9
Windows 10 64 bit. (tried install with both 32 and 64 bits

MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.3.0 - Build 10.18.15.4274 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4400'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

**Comment by codewarrior0** [comment]
Fixed in 3ad11dc0c7619ac067995c0896ef76d72ebbf0c0
