### ISSUE TITLE
MCEDIT2.0.0alpha919-wont open

### ISSUE THREAD

**Issue by poopys** [mcedit/mcedit2#196]
they told me to send you this

MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.13399 Compatibility Profile Context 15.201.1151.1008 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon R7 200 Series'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

**Comment by codewarrior0** [comment]
Fixed in 3ad11dc0c7619ac067995c0896ef76d72ebbf0c0
