### ISSUE TITLE
Errors and Bugs

### ISSUE THREAD

**Issue by sinanisler** [mcedit/mcedit2#204]
Hello,
I'm using this alpha mcedit 2 to much because I like the way designing 3D with it. 
That why I see so much bug and error 
So I will share my crashes here and I will try to explan what I was doing and why crash happen. :) 
So you can see the problem easy and fix faster.

**Error explanation**:  I selected a long 1x1x34 block and try to replace/fill with red wool. When I select the wool and I press fill it and program crashed.

**Error Code:**
```
MCEdit version: 2.0.0alpha-921
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 353.30 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 750 Ti/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\widgets\blockpicker.py", line 317, in showPicker (self is a BlockTypeButton)
  File "mcedit2\widgets\blockpicker.py", line 312, in blocks (self is a BlockTypeButton)
  File "mcedit2\widgets\blockpicker.py", line 283, in updateView (self is a BlockTypeButton)
AttributeError: 'EditorSession' object has no attribute 'textureAtlas'
```

**Comment by codewarrior0** [comment]
This should be fixed now. The block button was remembering a previously closed editing session.
