### ISSUE TITLE
error

### ISSUE THREAD

**Issue by colt05** [mcedit/mcedit2#208]
Hi. I keep getting this error (after updating):
```
Traceback (most recent call last):
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\editorapp.py", line 366, in didFinishLaunching (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 699, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 456, in __init__ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 514, in _updateVersionsAndResourcePacks (self is a EditorSession)
  File "mcedit2\util\minecraftinstall.py", line 153, in getCurrentInstall (self is a MCInstallGroup)
  File "mcedit2\util\minecraftinstall.py", line 150, in getInstall (self is a MCInstallGroup)
IndexError: list index out of range
```

**Comment by codewarrior0** [comment]
Version?

**Comment by colt05** [comment]
2.0.0 alpha 921. Lol didn't realize 2 more versions were released yesterday

**Comment by codewarrior0** [comment]
Fixed
