### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by compiledtom** [mcedit/mcedit2#209]
I tried both .919 and .921. .921 doesn't give me any info, just the generic Windows "This program has stopped working."  

919 gives me a litle more detail. The error dialog comes up immediately on start, so there's no useful screen shots. I just get this message.

MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.0 NVIDIA 359.06 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GPU/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

**Comment by codewarrior0** [comment]
Could you try build 932 and tell me if it still happens?

**Comment by codewarrior0** [comment]
Not enough info. Follow up if this issue happens in more recent builds.
