### ISSUE TITLE
Startup halted

### ISSUE THREAD

**Issue by WhiteNyte** [mcedit/mcedit2#212]
http://pastebin.com/zFKEM5ep  (full error report)

MCEdit Version Number - 2.0.0alpha-921
Minecraft Version Number - Minecraft 1.8.8
Operating System Version - Windows 8.1
 
 
Command line coding window comes up, rolls through the commands/returns and goes away.
 
GUI comes up and starts loading, then this error comes up:

Unhandled Exception
 
Traceback (most recent call last):
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\editorapp.py", line 366, in didFinishLaunching (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 699, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 149, in __init__ (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 226, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 62, in findAdapter  
ValueError: Cannot detect type of file C:\Users\Daniel\Documents\Minecraft\mcedit2-win64-2.0.0alpha-921\mcedit2.exe.

**Comment by codewarrior0** [comment]
Fixed
