### ISSUE TITLE
I cant open it at all it just comes up with error messege here is msg

### ISSUE THREAD

**Issue by ShadowKnight2904** [mcedit/mcedit2#214]
MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.4
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.4.0 NVIDIA 345.01 (4, 4)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GPU/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\editorapp.py", line 366, in didFinishLaunching (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 699, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 149, in __init__ (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 226, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 62, in findAdapter  
ValueError: Cannot detect type of file C:\Users\Daniel\Desktop\mcedit2-win64-2.0.0alpha-919\mcedit2.exe.

**Comment by ShadowKnight2904** [comment]
PLEASE HELP

**Comment by 343Modding** [comment]
It says 64 bit only, you're using 32 bit.

**Comment by codewarrior0** [comment]
Fixed.
