### ISSUE TITLE
Unhandled Exception while attempting to load a schematic

### ISSUE THREAD

**Issue by ShadyEntry** [mcedit/mcedit2#216]
MCEdit version: 2.0.0alpha-932
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.3.0 - Build 10.18.15.4256 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4600'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldlist.py", line 324, in openWorldClicked (self is a WorldListWidget)
  File "mcedit2\editorapp.py", line 781, in chooseOpenWorld (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 699, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 174, in __init__ (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 264, in requireRevisions (self is a WorldEditor)
AttributeError: 'SchematicFileAdapter' object has no attribute 'requireRevisions'

**Comment by codewarrior0** [comment]
Not a startup error. Directly editing schematics is not yet implemented.
