### ISSUE TITLE
KeyError: u'attached=false,facing=south,powered=false,suspended=false' when loading a world after using Configure Installs dialog

### ISSUE THREAD

**Issue by juozaspo** [mcedit/mcedit2#218]
On linux (using virtualenv), if Configure Installs dialog was used, trying to load the world on mcedit2 fails with KeyError: u'attached=false,facing=south,powered=false,suspended=false'
The error does not happen before using the Configure Installs dialog.
Next subsequent startups leads to same error and hitting Ctrl+C on console halts the program as window is still visible when the crash occurs. Full log below

```
[INFO][main.py:170]:MCEdit2 version v2.0-tech-demo-1167-g6055a4d starting...
[INFO][acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[INFO][settings.py:100]:Loading app settings from /home/juozas/mcedit2/MCEdit User Data/mcedit2.ini
[INFO][loadablechunks.py:17]:Making checkerboard texture...
[INFO][minecraftinstall.py:246]:Checking install at /home/juozas/.minecraft
[INFO][minecraftinstall.py:253]:Found versions:
[u'1.8.9', u'1.6.4', u'1.8.5', u'1.8.6', u'1.8.4', u'1.8.1', u'1.9.1-pre3', u'1.8.2', u'1.9', u'1.8.8', u'1.8.7', u'1.8.3', u'1.7.10']
[INFO][minecraftinstall.py:246]:Checking install at /home/juozas/.minecraft
[INFO][minecraftinstall.py:253]:Found versions:
[u'1.8.9', u'1.6.4', u'1.8.5', u'1.8.6', u'1.8.4', u'1.8.1', u'1.9.1-pre3', u'1.8.2', u'1.9', u'1.8.8', u'1.8.7', u'1.8.3', u'1.7.10']
[WARNING][editorapp.py:91]:UserFilesDirectory: /home/juozas/mcedit2/MCEdit User Data
[INFO][editorapp.py:99]:Loaded translator.
[INFO][editorapp.py:108]:Loaded stylesheet.
[INFO][editorapp.py:120]:Loaded main window.
[INFO][editorapp.py:176]:Loaded panels.
[INFO][editorapp.py:219]:Loaded debug widgets.
[INFO][editorapp.py:269]:Loaded menus.
[INFO][worldlist.py:94]:Size hint: PySide.QtCore.QSize(145, 79)
[INFO][worldlist.py:95]:Size : PySide.QtCore.QSize(145, 100)
[INFO][worldlist.py:339]:Scanning /home/juozas/.minecraft/saves for worlds...
[INFO][editorapp.py:279]:Loaded world list.
[INFO][editorapp.py:298]:Loaded status bar.
[INFO][editorapp.py:595]:Updating recent files menu: (1) [u'/home/juozas/.minecraft/saves/Creative 1']
[INFO][editorapp.py:610]:Adding Creative 1
[INFO][editorapp.py:305]:Loaded settings.
[WARNING][configure_blocks.py:121]:Failed to read definitions file defined_blocks.json
[INFO][editorapp.py:327]:Loaded app dialogs.
[INFO][editorapp.py:335]:Loading timer started
[INFO][editorapp.py:345]:Finding plugins
[INFO][plugins.py:203]:Loading plugins from /home/juozas/mcedit2/src/plugins
[INFO][plugins.py:110]:Trying to load plugin from koch.py
[INFO][plugins.py:121]:Loaded koch.py (Koch Snowflake)
[INFO][plugins.py:110]:Trying to load plugin from hilbert.py
[INFO][plugins.py:121]:Loaded hilbert.py (Hilbert Curve)
[INFO][plugins.py:110]:Trying to load plugin from city.py
[INFO][plugins.py:121]:Loaded city.py (GFX: City)
[INFO][plugins.py:110]:Trying to load plugin from storagedrawers.py
[INFO][plugins.py:121]:Loaded storagedrawers.py (storagedrawers)
[INFO][editorapp.py:362]:Opening worlds from command line.
[INFO][qglcontext.py:53]:Obtained a GL context with this format:
Valid: True
Version: 1.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 3.3.0 NVIDIA 340.96 (3, 3)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 210/PCIe/SSE2'

[INFO][worldview.py:909]:LAYER Blocks VISIBLE True
[INFO][worldview.py:909]:LAYER MonsterLocations VISIBLE False
[INFO][worldview.py:909]:LAYER Items VISIBLE True
[INFO][worldview.py:909]:LAYER TileEntities VISIBLE True
[INFO][worldview.py:909]:LAYER TileEntityLocations VISIBLE False
[INFO][worldview.py:909]:LAYER CommandBlockColors VISIBLE True
[INFO][worldview.py:909]:LAYER CommandBlockLocations VISIBLE False
[INFO][worldview.py:909]:LAYER ItemFrames VISIBLE True
[INFO][worldview.py:909]:LAYER TileTicks VISIBLE False
[INFO][worldview.py:909]:LAYER ChunkSections VISIBLE False
[INFO][worldview.py:909]:LAYER HeightMap VISIBLE False
[INFO][worldview.py:909]:LAYER Places Where Creepers Can Spawn VISIBLE False
[INFO][worldview.py:227]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'/home/juozas/.minecraft/saves/Creative 1'))
[INFO][chunkloader.py:155]:Added: client MinimapWorldView(u'Creative 1: ')
[INFO][worldlist.py:391]:Centering on single-player player.
[INFO][worldlist.py:410]:Switched world view
[INFO][worldeditor.py:427]:Scanning for regions in /home/juozas/.minecraft/saves/Creative 1...
[INFO][worldeditor.py:436]:Dim : Found 5642 chunks in 0.14 seconds.
[INFO][worldlist.py:423]:Removing view from WorldListWidget
[INFO][worldview.py:200]:Deallocating GL resources for worldview MinimapWorldView(u'Creative 1: ')
[INFO][minecraftinstall.py:298]:Created ResourceLoader with search path:
/home/juozas/.minecraft/versions/1.9.1-pre3/1.9.1-pre3.jar (82f4c9f6ddd4a148c2db9659252056ce)
[INFO][editorsession.py:674]:Loading block models...
[INFO][editorsession.py:674]:Loading block models 0/1388
[INFO][editorsession.py:674]:Loading block models 100/1388
[INFO][editorsession.py:674]:Loading block models 200/1388
[INFO][editorsession.py:674]:Loading block models 300/1388
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file fire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file redstone_wire, skipping...
[INFO][editorsession.py:674]:Loading block models 400/1388
[INFO][editorsession.py:674]:Loading block models 500/1388
[WARNING][editorsession.py:674]:'variants' key not found in states file fence, skipping...
[INFO][editorsession.py:674]:Loading block models 600/1388
[WARNING][editorsession.py:674]:'variants' key not found in states file iron_bars, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file glass_pane, skipping...
[INFO][editorsession.py:674]:Loading block models 700/1388
[WARNING][editorsession.py:674]:'variants' key not found in states file nether_brick_fence, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[WARNING][editorsession.py:674]:'variants' key not found in states file brewing_stand, skipping...
[INFO][editorsession.py:674]:Loading block models 800/1388
[ERROR][main.py:192]:Unhandled Exception: 
	u'attached=false,facing=south,powered=false,suspended=false'
Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/editorapp.py", line 755, in viewWorldFromList (self is a MCEditApp)
    self.loadFile(filename, readonly=True)
  File "/home/juozas/mcedit2/src/mcedit2/editorapp.py", line 699, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/home/juozas/mcedit2/src/mcedit2/editorsession.py", line 364, in __init__ (self is a EditorSession)
    self.setConfiguredBlocks(configuredBlocks)  # Must be called after resourceLoader is in place
  File "/home/juozas/mcedit2/src/mcedit2/editorsession.py", line 670, in setConfiguredBlocks (self is a EditorSession)
    self.reloadModels()
  File "/home/juozas/mcedit2/src/mcedit2/editorsession.py", line 674, in reloadModels (self is a EditorSession)
    self.blockModels = BlockModels(self.worldEditor.blocktypes, self.resourceLoader)
  File "src/mcedit2/rendering/blockmodels.pyx", line 224, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:5001)  
    result = self.loadResourceVariant(resourcePath, resourceVariant)
  File "src/mcedit2/rendering/blockmodels.pyx", line 410, in mcedit2.rendering.blockmodels.BlockModels.loadResourceVariant (src/mcedit2/rendering/blockmodels.c:7961)  
    variantDict = variants[resourceVariant]
KeyError: u'attached=false,facing=south,powered=false,suspended=false'
[ERROR][main.py:192]:Unhandled Exception: 
	
Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/util/profiler.py", line 70, in _wrapper (self is a Profiler)
    @functools.wraps(func)
KeyboardInterrupt
```

**Comment by juozaspo** [comment]
still causing error (popup after trying to load (View) a world after using configure installs wth.

```
An error occurred while opening /home/juozas/.minecraft/saves/Creative 1
u'attached=false,facing=south,powered=false,suspended=false'

Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/editorapp.py", line 699, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/home/juozas/mcedit2/src/mcedit2/editorsession.py", line 364, in __init__ (self is a EditorSession)
    self.setConfiguredBlocks(configuredBlocks)  # Must be called after resourceLoader is in place
  File "/home/juozas/mcedit2/src/mcedit2/editorsession.py", line 672, in setConfiguredBlocks (self is a EditorSession)
    self.reloadModels()
  File "/home/juozas/mcedit2/src/mcedit2/editorsession.py", line 676, in reloadModels (self is a EditorSession)
    self.blockModels = BlockModels(self.worldEditor.blocktypes, self.resourceLoader)
  File "src/mcedit2/rendering/blockmodels.pyx", line 224, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:5001)  
    self.blockStatesByResourcePathVariant[resourcePath, resourceVariant].append((internalName, blockState))
  File "src/mcedit2/rendering/blockmodels.pyx", line 410, in mcedit2.rendering.blockmodels.BlockModels.loadResourceVariant (src/mcedit2/rendering/blockmodels.c:7961)  
    except ResourceNotFound as e:
KeyError: u'attached=false,facing=south,powered=false,suspended=false'
```

Can't load a single world save :/
