### ISSUE TITLE
ValueError: too many values to unpack on trying to select a block after first world load of first mcedit startup.

### ISSUE THREAD

**Issue by juozaspo** [mcedit/mcedit2#219]
On linux (using virtualenv), after installation and succefull startup and world load, clicking on a block mcedit crash with error ValueError: too many values to unpack. Closing the world then reopen seems to be temporary fix. Full log below:

```
[WARNING][editorapp.py:91]:UserFilesDirectory: /home/juozas/mcedit2/MCEdit User Data
[WARNING][configure_blocks.py:121]:Failed to read definitions file defined_blocks.json
Could not parse stylesheet of widget 0x6bb0560
Could not parse stylesheet of widget 0x8361820
Could not parse stylesheet of widget 0x54c0ea0
Could not parse stylesheet of widget 0x89c4ed0
Could not parse stylesheet of widget 0x7b984e0
Could not parse stylesheet of widget 0x7b9d0f0
Could not parse stylesheet of widget 0x7ba1dc0
Could not parse stylesheet of widget 0x7ba6a10
Could not parse stylesheet of widget 0x7bab570
Could not parse stylesheet of widget 0x7bb00f0
Could not parse stylesheet of widget 0x60b6520
QMainWindow::addDockWidget: invalid 'area' argument
[ERROR][main.py:192]:Unhandled Exception: 
	too many values to unpack
Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/worldview/worldview.py", line 591, in paintGL (self is a CameraWorldView)
    rendernode.renderScene(self.renderGraph)
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 274, in renderScene  
    renderNode.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile (self is a RenderNode)
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile (self is a RenderNode)
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile (self is a RenderNode)
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile (self is a RenderNode)
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile (self is a RenderNode)
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 103, in compile (self is a SelectionFaceRenderNode)
    self.displayList.compile(self.draw)
  File "/home/juozas/mcedit2/src/mcedit2/util/glutils.py", line 145, in compile (self is a DisplayList)
    self._compile(drawFunc)
  File "/home/juozas/mcedit2/src/mcedit2/util/glutils.py", line 150, in _compile (self is a DisplayList)
    drawFunc()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 117, in draw (self is a SelectionFaceRenderNode)
    self.drawSelf()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/selection.py", line 353, in drawSelf (self is a SelectionFaceRenderNode)
    r, g, b = self.sceneNode.wireColor
ValueError: too many values to unpack
Logging level set
Logging to /home/juozas/mcedit2/MCEdit User Data/mcedit.log
Setting up console handler
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/main.py", line 207, in excepthook
    showErrorDialog("Unhandled Exception", (exc_type, exc_value, exc_tb), fatal=True)
  File "/home/juozas/mcedit2/src/mcedit2/dialogs/error_dialog.py", line 26, in showErrorDialog
    grabber.releaseMouse()
AttributeError: 'NoneType' object has no attribute 'releaseMouse'

Original exception was:
Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/worldview/worldview.py", line 591, in paintGL
    rendernode.renderScene(self.renderGraph)
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 274, in renderScene
    renderNode.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 96, in compile
    node.compile()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 103, in compile
    self.displayList.compile(self.draw)
  File "/home/juozas/mcedit2/src/mcedit2/util/glutils.py", line 145, in compile
    self._compile(drawFunc)
  File "/home/juozas/mcedit2/src/mcedit2/util/glutils.py", line 150, in _compile
    drawFunc()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/scenegraph/rendernode.py", line 117, in draw
    self.drawSelf()
  File "/home/juozas/mcedit2/src/mcedit2/rendering/selection.py", line 353, in drawSelf
    r, g, b = self.sceneNode.wireColor
ValueError: too many values to unpack
[ERROR][main.py:192]:Unhandled Exception: 
	
Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/worldview/camera.py", line 140, in tickCamera (self is a CameraKeyControls)
    def tickCamera(self):
KeyboardInterrupt
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
```

**Comment by codewarrior0** [comment]
Should be fixed in the latest release.
