### ISSUE TITLE
Configure Installs fails with AttributeError: 'MinecraftInstallsDialog' object has no attribute 'snapshotsCheckBox' after last update

### ISSUE THREAD

**Issue by juozaspo** [mcedit/mcedit2#222]
updated mcedit2 via "git pull" command. Running fine until clicking Configure Installs on start. Instant error popup.

```
MCEdit version: v2.0-tech-demo-1180-g37fc89a
Python version: 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]
Platform: linux2
System version: Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
Processor: x86_64

Obtained a GL context with this format:
Valid: True
Version: 1.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 3.3.0 NVIDIA 340.96 (3, 3)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 210/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/worldlist.py", line 518, in configureClicked (self is a WorldListWidget)
    installsWidget = MinecraftInstallsDialog()
  File "/home/juozas/mcedit2/src/mcedit2/util/minecraftinstall.py", line 519, in __init__ (self is a MinecraftInstallsDialog)
    self.snapshotsCheckBox.setChecked(allowSnapshotsOption.value())
AttributeError: 'MinecraftInstallsDialog' object has no attribute 'snapshotsCheckBox'
```

p.s. Using this custom mcedit launcher (.sh - in mcedit directory) - typing commands manually is annoying

```
#!/bin/bash
. ENV/bin/activate
mcedit2 > mcedit2.log 2>&1 
deactivate
```

**Comment by codewarrior0** [comment]
Should be fixed in 98fd8f5cc24a9751a01974f91b5e9dec87847161
