### ISSUE TITLE
Cannot start mcedit 2.0.0 64 bit, unhandled exception in main.py, unable to load OpenGL library

### ISSUE THREAD

**Issue by TheRealEaglebird** [mcedit/mcedit2#224]
I've searched around for information regarding my specific error but haven't found anything 100% pertinent. I've tried installing various versions of python, pyopengl, and my video card drivers to rectify the problem but I still run into this unhandled exception.

I'm on Windows 7 Ultimate, 64 bit, trying to run the 64 bit version of mcedit 2.0.0. The 32 bit version loads and runs, but for some reason will not save the world or provide a save dialog. The error I'm reporting though is as follows:

>[INFO][main.py:173]:MCEdit2 version 2.0.0alpha-1007 starting...
[ERROR][main.py:195]:Unhandled Exception: 
	('Unable to load OpenGL library', 193, '%1 is not a valid Win32 application', 'C:\\Windows\\SysWOW64\\opengl32.dll', 'C:\\Windows\\SysWOW64\\opengl32.dll')
Traceback (most recent call last):
  File "mcedit2\main.py", line 218, in <module>  
  File "mcedit2\main.py", line 214, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 184, in startup  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\editorapp.py", line 14, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\plugins.py", line 11, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\editortools\generate.py", line 12, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\handles\boxhandle.py", line 10, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\rendering\scenegraph\scenenode.py", line 8, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 9, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "site-packages\OpenGL\GL\__init__.py", line 3, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "site-packages\OpenGL\error.py", line 12, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "site-packages\OpenGL\platform\__init__.py", line 35, in <module>  
  File "site-packages\OpenGL\platform\__init__.py", line 32, in _load  
  File "site-packages\OpenGL\platform\baseplatform.py", line 92, in install (self is a Win32Platform)
  File "site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__ (self is a lazy_property)
  File "site-packages\OpenGL\platform\win32.py", line 106, in GetCurrentContext (self is a Win32Platform)
  File "site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__ (self is a lazy_property)
  File "site-packages\OpenGL\platform\win32.py", line 31, in GL (self is a Win32Platform)
ImportError: ('Unable to load OpenGL library', 193, '%1 is not a valid Win32 application', 'C:\\Windows\\SysWOW64\\opengl32.dll', 'C:\\Windows\\SysWOW64\\opengl32.dll')
<

This stops the program and in a normal instance closes the command window, though I have it open in a prompt.

**Comment by codewarrior0** [comment]
Would you mind posting your entire `mcedit.log`? 

If you're running the 64-bit version, it should not be loading DLL files in `SysWOW64`. That folder only has 32-bit DLLs, despite the name.

**Comment by TheRealEaglebird** [comment]
That is the entirety of mcedit.log, but this is a full log as copied from the command line:
http://pastebin.com/NLB9H6q2
with the wordwrap removed.

**Comment by codewarrior0** [comment]
Do you by any chance have `C:\Windows\SysWOW64` in your PATH environment variable?

**Comment by TheRealEaglebird** [comment]
I had %systemroot%\SysWOW64 in my user variables but not in the system path. I removed it and tried again to the same result.

**Comment by codewarrior0** [comment]
When you tried again, how did you start MCEdit? If you started it from a command prompt window that was open before you changed your environs, that command prompt will still have the old environs.

**Comment by TheRealEaglebird** [comment]
Why I didn't remember that I wouldn't know but yes that fixed the issue; I fired up a new prompt and it started right up.

Appreciate the help, I would've been stuck using 32 bit if I hadn't asked!

**Comment by codewarrior0** [comment]
Thanks for the info. I'll have to patch PyOpenGL to work around this problem.

I don't suppose you have any idea why SysWOW64 was in your PATH? 

(It shouldn't be in the PATH because Windows will redirect DLL loading to that folder as needed.)

**Comment by TheRealEaglebird** [comment]
I don't, but my guess is something among the myriad of tools and widgets I've installed may have added it. That, or in some misguided information I may have added it long ago.
