### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'viewMouseMove' error on close after some messing up and exploring (world loaded as read-only)

### ISSUE THREAD

**Issue by juozaspo** [mcedit/mcedit2#225]
Was testing new mcedit2 version on my Ubuntu 64bit machine, clicked the "x" button near world title after doing some exploring and other messing arround, BAM there's an error out of nowhere. The world was loaded as read-only (View mode)

```
MCEdit version: v2.0-tech-demo-1182-ge4bb8ee
Python version: 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]
Platform: linux2
System version: Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
Processor: x86_64

Obtained a GL context with this format:
Valid: True
Version: 1.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 3.3.0 NVIDIA 340.96 (3, 3)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 210/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "/home/juozas/mcedit2/src/mcedit2/worldview/worldview.py", line 488, in mouseMoveEvent (self is a CameraWorldView)
    action.mouseMoveEvent(event)
  File "/home/juozas/mcedit2/src/mcedit2/worldview/viewaction.py", line 214, in mouseMoveEvent (self is a TrackingMouseAction)
    self.editorTab.editorSession.viewMouseMove(event)
AttributeError: 'NoneType' object has no attribute 'viewMouseMove'
```

**Comment by codewarrior0** [comment]
Should be fixed.
