### ISSUE TITLE
Hmm.. It crashes in MCEdit 2.x at startup.

### ISSUE THREAD

**Issue by Devonnuri** [mcedit/mcedit2#229]
I tried almost of the 2.X versions but, it crashes all when it starts up.
I do my best kinda checked of my drive space, tried to 32bit version, deleted document\MCEdit folder, rebooted...
But nothing happened :(

Command Prompt:

Setting up console handler
[WARNING][editorapp.py:91]:UserFilesDirectory: D:\mcedit2-win32-2.0.0alpha-1007\MCEdit 2 Files
[ERROR][main.py:195]:Unhandled Exception:
        'ascii' codec can't decode byte 0xb5 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "mcedit2\main.py", line 218, in <module>
  File "mcedit2\main.py", line 214, in main
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 186, in startup
  File "mcedit2\editorapp.py", line 96, in __init__ (self is a MCEditApp)
  File "mcedit2\util\resources.py", line 67, in resourcePath
  File "ntpath.py", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 7: ordinal not in range(128)

My Laptop Specification:
Windows 10 Education 64 bit, GTX 970M, i7-6700HQ : MSI GE72 6QF

**Comment by codewarrior0** [comment]
Fixed.
