### ISSUE TITLE
Unhandled Exception when adding a String to NBT data

### ISSUE THREAD

**Issue by brennced** [mcedit/mcedit2#230]
### Steps to reproduce

1. Open any world with MCEdit
2. Select a dropper with the "Inspect Block tool"
3. Try adding a string NBT-Tag to the root of the dropper
4. The error occurs

**Error Details:**
```
MCEdit version: 2.0.0alpha-1018
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 355.82 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 960/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\widgets\nbttree\nbteditor.py", line 273, in rowsDidInsert (self is a NBTEditorWidget)
  File "mcedit2\widgets\nbttree\nbteditor.py", line 253, in tagNameForUndo (self is a NBTEditorWidget)
AttributeError: 'NoneType' object has no attribute 'tag'
```

Minecraft Version: `1.9.4/vanilla`

**Comment by codewarrior0** [comment]
Fixed
