### ISSUE TITLE
World Load unresponsive at 28% every single time

### ISSUE THREAD

**Issue by Ranger-Hero587** [mcedit/mcedit2#232]
I'm using 2.0.0alpha-1018 which is the latest on the date this was published. This is on a windows10 hp laptop. When ever I try to view or edit any world the loading will always stop at 28%, it get there in second & then soon after becomes unresponsive.
![fuck](https://cloud.githubusercontent.com/assets/19617683/15624608/3e965a20-24e0-11e6-9293-3a9bed9cedf1.PNG)
What can i do to fix this?

**Comment by codewarrior0** [comment]
Post the "mcedit.log" file found in the "MCEdit User Data" folder next to the application.

**Comment by arliben** [comment]
I get this every time, too, on a certain world.

Unhandled Exception

Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorapp.py", line 747, in editWorldFromList (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorapp.py", line 698, in loadFile (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 362, in __init__ (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 670, in setConfiguredBlocks (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 674, in reloadModels (self is a EditorSession)
  File "mcedit2\rendering\blockmodels.pyx", line 224, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:4878)  
    result = self.loadResourceVariant(resourcePath, resourceVariant)
  File "mcedit2\rendering\blockmodels.pyx", line 410, in mcedit2.rendering.blockmodels.BlockModels.loadResourceVariant (src/mcedit2/rendering/blockmodels.c:7653)  
    variantDict = variants[resourceVariant]
KeyError: u'attached=false,facing=south,powered=false,suspended=false'

**Comment by codewarrior0** [comment]
That traceback is from an older version. If this still happens, open a new issue and include all of the required info.
