### ISSUE TITLE
PlayerNotFound: None

### ISSUE THREAD

**Issue by growlf** [mcedit/mcedit2#24]
The app opens fine, with only a warning:

    (pve)tester@testsys:~/mcedit2$ mcedit2 
    Logging level set
    Logging to /home/tester/MCEdit User Data/mcedit.log
    Setting up console handler
    [WARNING][editorapp.py:77]:UserFilesDirectory: /home/tester/MCEdit User Data

Then when I attempt to select and edit any map, I get this and the app crashes:

    Exception AttributeError: "'RevisionHistory' object has no attribute 'nodes'" in  ignored
    [ERROR][main.py:125]:Unhandled Exception: 
	    None
    Traceback (most recent call last):
      File "/home/tester/mcedit2/src/mcedit2/editorapp.py", line 567, in editWorldFromList (self is a MCEditApp)
        self.loadFile(filename)
      File "/home/tester/mcedit2/src/mcedit2/editorapp.py", line 534, in loadFile (self is a MCEditApp)
        session = EditorSession(filename, self.worldList.getSelectedIVP(), readonly=readonly)
      File "/home/tester/mcedit2/src/mcedit2/editorsession.py", line 169, in __init__ (self is a EditorSession)
        self.playerPanel = PlayerPanel(self)
      File "/home/tester/mcedit2/src/mcedit2/panels/player.py", line 70, in __init__ (self is a PlayerPanel)
        self.initPropertiesWidget()
      File "/home/tester/mcedit2/src/mcedit2/panels/player.py", line 78, in initPropertiesWidget (self is a PlayerPanel)
        model = PropertyListModel(self.selectedPlayer.rootTag)
      File "/home/tester/mcedit2/src/mcedit2/panels/player.py", line 160, in selectedPlayer (self is a PlayerPanel)
        return self.editorSession.worldEditor.getPlayer(self.selectedUUID)
      File "/home/tester/mcedit2/src/mceditlib/worldeditor.py", line 470, in getPlayer (self is a WorldEditor)
        player = self.adapter.getPlayer(playerUUID)
      File "/home/tester/mcedit2/src/mceditlib/anvil/adapter.py", line 837, in getPlayer (self is a AnvilWorldAdapter)
        return AnvilPlayerRef(self, playerUUID)
      File "/home/tester/mcedit2/src/mceditlib/anvil/adapter.py", line 918, in __init__ (self is a AnvilPlayerRef)
        self.rootTag = adapter.getPlayerTag(playerUUID)
      File "/home/tester/mcedit2/src/mceditlib/anvil/adapter.py", line 861, in getPlayerTag (self is a AnvilWorldAdapter)
        raise PlayerNotFound(playerUUID)
    PlayerNotFound: None
    (pve)tester@testsys:~/mcedit2$ 

I am running Ubuntu 14.10, with all updates applied, Python 2.7.6 virtual environment with requirements installed using 'pip -r requirements.txt'.

**Comment by codewarrior0** [comment]
What Minecraft version is used to play the worlds? And is it single-player or a multiplayer server?

**Comment by codewarrior0** [comment]
Try the latest revision (`git pull origin master`) and let me know if it's fixed.
