### ISSUE TITLE
MCE2 Crashes on load - linux x64

### ISSUE THREAD

**Issue by EvilSupahFly** [mcedit/mcedit2#240]
Running F6021F1, MCE2 fails to start. Running Ubuntu Linux 15.10 x64. 

Output from terminal:

```
seann@black-beast:~/mcedit_v2 $ mcedit2
fatal: Not a git repository (or any parent up to mount point /home/seann)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Logging level set
Logging to /home/seann/.mcedit2/mcedit.log
Setting up console handler
[ERROR][main.py:195]:Unhandled Exception: 
	numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>  
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main  
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup  
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>  
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>  
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 17, in <module>  
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 13, in <module>  
    from mcedit2.rendering import chunkupdate
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/chunkupdate.py", line 8, in <module>  
    from mcedit2.rendering.modelmesh import BlockModelMesh
  File "__init__.pxd", line 155, in init mcedit2.rendering.modelmesh (src/mcedit2/rendering/modelmesh.c:25665)  
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 209, in excepthook
    from mcedit2.dialogs.error_dialog import showErrorDialog
  File "/home/seann/mcedit_v2/src/mcedit2/dialogs/error_dialog.py", line 12, in <module>
    from mcedit2.ui.dialogs.error_dialog import Ui_errorDialog
ImportError: No module named error_dialog

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 17, in <module>
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 13, in <module>
    from mcedit2.rendering import chunkupdate
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/chunkupdate.py", line 8, in <module>
    from mcedit2.rendering.modelmesh import BlockModelMesh
  File "__init__.pxd", line 155, in init mcedit2.rendering.modelmesh (src/mcedit2/rendering/modelmesh.c:25665)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

Contents of Log File:
```
[INFO][main.py:173]:MCEdit2 version 5.0.6 starting...
[INFO][acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[ERROR][main.py:195]:Unhandled Exception: 
	numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>  
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main  
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup  
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>  
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>  
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 17, in <module>  
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 13, in <module>  
    from mcedit2.rendering import chunkupdate
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/chunkupdate.py", line 8, in <module>  
    from mcedit2.rendering.modelmesh import BlockModelMesh
  File "__init__.pxd", line 155, in init mcedit2.rendering.modelmesh (src/mcedit2/rendering/modelmesh.c:25665)  
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

Pip reports the following versions:
```
Cython (0.24)
numpy (1.9.3)
arrow (0.7.0)
PySide (1.2.4)
PyOpenGL (3.1.0)
ipython (4.2.0)
qtconsole (4.2.1)
Pygments (2.1.3)
pyzmq (15.2.0)
Pastebin (1.1.1)
```

**Comment by codewarrior0** [comment]
Your numpy version seems to have changed recently. You need to run `python setup.py build_ext -i` to rebuild the .pyd modules.

**Comment by EvilSupahFly** [comment]
```
seann@black-beast:~/mcedit_v2 $ python setup.py build_ext -i
running build_ext
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/blockmodels.so -> src/mcedit2/rendering
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/modelmesh.so -> src/mcedit2/rendering
running build_ext
copying build/lib.linux-x86_64-2.7/mceditlib/nbt.so -> src/mceditlib
copying build/lib.linux-x86_64-2.7/mceditlib/relight/with_cython.so -> src/mceditlib/relight
seann@black-beast:~/mcedit_v2 $ mcedit2
fatal: Not a git repository (or any parent up to mount point /home/seann)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
GL Errors enabled!
Logging level set
Logging to /home/seann/.mcedit2/mcedit.log
Setting up console handler
[ERROR][main.py:195]:Unhandled Exception: 
	numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>  
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main  
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup  
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>  
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>  
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 17, in <module>  
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 13, in <module>  
    from mcedit2.rendering import chunkupdate
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/chunkupdate.py", line 8, in <module>  
    from mcedit2.rendering.modelmesh import BlockModelMesh
  File "__init__.pxd", line 155, in init mcedit2.rendering.modelmesh (src/mcedit2/rendering/modelmesh.c:25665)  
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 209, in excepthook
    from mcedit2.dialogs.error_dialog import showErrorDialog
  File "/home/seann/mcedit_v2/src/mcedit2/dialogs/error_dialog.py", line 12, in <module>
    from mcedit2.ui.dialogs.error_dialog import Ui_errorDialog
ImportError: No module named error_dialog

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 17, in <module>
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 13, in <module>
    from mcedit2.rendering import chunkupdate
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/chunkupdate.py", line 8, in <module>
    from mcedit2.rendering.modelmesh import BlockModelMesh
  File "__init__.pxd", line 155, in init mcedit2.rendering.modelmesh (src/mcedit2/rendering/modelmesh.c:25665)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

**Comment by codewarrior0** [comment]
The first few lines show that it didn't actually rebuild the modules. Maybe you need to do `python setup.py build_ext -i --force`

**Comment by EvilSupahFly** [comment]
I'll give it a try :)

**Comment by EvilSupahFly** [comment]
Hmmmm

```
seann@black-beast:~/mcedit_v2 $ python setup.py build_ext -i --force
running build_ext
building 'mcedit2.rendering.blockmodels' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/mcedit2/rendering/blockmodels.c -o build/temp.linux-x86_64-2.7/src/mcedit2/rendering/blockmodels.o
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/mcedit2/rendering/blockmodels.c:274:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from src/mcedit2/rendering/blockmodels.c:275:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
src/mcedit2/rendering/blockmodels.c: In function ‘__pyx_pf_7mcedit2_9rendering_11blockmodels_11BlockModels_16cookQuads’:
src/mcedit2/rendering/blockmodels.c:12698:54: warning: ‘__pyx_v_meta’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         ((__pyx_v_self->cookedModelsByID[__pyx_v_ID])[__pyx_v_meta]) = __pyx_v_modelQuads;
                                                      ^
src/mcedit2/rendering/blockmodels.c:12698:54: warning: ‘__pyx_v_ID’ may be used uninitialized in this function [-Wmaybe-uninitialized]
src/mcedit2/rendering/blockmodels.c: In function ‘__pyx_pf_7mcedit2_9rendering_11blockmodels_11BlockModels_6__init__’:
src/mcedit2/rendering/blockmodels.c:36304:20: warning: ‘__pyx_v_variantYrot’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return PyInt_FromLong((long) value);
                    ^
src/mcedit2/rendering/blockmodels.c:3998:9: note: ‘__pyx_v_variantYrot’ was declared here
   short __pyx_v_variantYrot;
         ^
src/mcedit2/rendering/blockmodels.c:36304:20: warning: ‘__pyx_v_variantXrot’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return PyInt_FromLong((long) value);
                    ^
src/mcedit2/rendering/blockmodels.c:3997:9: note: ‘__pyx_v_variantXrot’ was declared here
   short __pyx_v_variantXrot;
         ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/mcedit2/rendering/blockmodels.o -o build/lib.linux-x86_64-2.7/mcedit2/rendering/blockmodels.so
building 'mcedit2.rendering.modelmesh' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/mcedit2/rendering/modelmesh.c -o build/temp.linux-x86_64-2.7/src/mcedit2/rendering/modelmesh.o
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/mcedit2/rendering/modelmesh.c:274:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/mcedit2/rendering/modelmesh.c:274:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from src/mcedit2/rendering/modelmesh.c:275:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
src/mcedit2/rendering/modelmesh.c: In function ‘__pyx_pf_7mcedit2_9rendering_9modelmesh_14BlockModelMesh_2createVertexArrays.isra.44’:
src/mcedit2/rendering/modelmesh.c:8828:70: warning: ‘__pyx_v_tintColor’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                   __pyx_v_color = (__pyx_v_color * (__pyx_v_tintColor[(2 - __pyx_v_channel)]));
                                                                      ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/mcedit2/rendering/modelmesh.o -o build/lib.linux-x86_64-2.7/mcedit2/rendering/modelmesh.so
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/blockmodels.so -> src/mcedit2/rendering
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/modelmesh.so -> src/mcedit2/rendering
running build_ext
building 'mceditlib.nbt' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/mceditlib/nbt.c -o build/temp.linux-x86_64-2.7/src/mceditlib/nbt.o
In file included from src/mceditlib/nbt.c:274:0:
/usr/include/python2.7/cStringIO.h:62:4: warning: ‘PycStringIO’ defined but not used [-Wunused-variable]
 } *PycStringIO;
    ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/mceditlib/nbt.o -o build/lib.linux-x86_64-2.7/mceditlib/nbt.so
building 'mceditlib.relight.with_cython' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/mceditlib/relight/with_cython.cpp -o build/temp.linux-x86_64-2.7/src/mceditlib/relight/with_cython.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/mceditlib/relight/with_cython.cpp:293:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/mceditlib/relight/with_cython.cpp:293:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘int _import_array()’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from src/mceditlib/relight/with_cython.cpp:294:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘int _import_umath()’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/mceditlib/relight/with_cython.o -o build/lib.linux-x86_64-2.7/mceditlib/relight/with_cython.so
copying build/lib.linux-x86_64-2.7/mceditlib/nbt.so -> src/mceditlib
copying build/lib.linux-x86_64-2.7/mceditlib/relight/with_cython.so -> src/mceditlib/relight

seann@android-d8da4abfed0f33bf:~/mcedit_v2 $ mcedit2
fatal: Not a git repository (or any parent up to mount point /home/seann)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Logging level set
Logging to /home/seann/.mcedit2/mcedit.log
Setting up console handler
[ERROR][main.py:195]:Unhandled Exception: 
	No module named block_picker_multiple
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>  
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main  
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup  
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>  
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>  
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 20, in <module>  
    from mcedit2.widgets.layout import Column
  File "/home/seann/mcedit_v2/src/mcedit2/widgets/__init__.py", line 7, in <module>  
    import blockpicker
  File "/home/seann/mcedit_v2/src/mcedit2/widgets/blockpicker.py", line 12, in <module>  
    from mcedit2.ui.widgets.block_picker_multiple import Ui_blockPickerMultiple
ImportError: No module named block_picker_multiple
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 209, in excepthook
    from mcedit2.dialogs.error_dialog import showErrorDialog
  File "/home/seann/mcedit_v2/src/mcedit2/dialogs/error_dialog.py", line 12, in <module>
    from mcedit2.ui.dialogs.error_dialog import Ui_errorDialog
ImportError: No module named error_dialog

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 9, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 214, in main
    app = startup()
  File "/home/seann/mcedit_v2/src/mcedit2/util/profiler.py", line 73, in _wrapper
    return func(*a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/main.py", line 184, in startup
    from mcedit2.editorapp import MCEditApp
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 14, in <module>
    from mcedit2 import plugins
  File "/home/seann/mcedit_v2/src/mcedit2/plugins/__init__.py", line 13, in <module>
    from mcedit2.editortools import generate
  File "/home/seann/mcedit_v2/src/mcedit2/editortools/generate.py", line 20, in <module>
    from mcedit2.widgets.layout import Column
  File "/home/seann/mcedit_v2/src/mcedit2/widgets/__init__.py", line 7, in <module>
    import blockpicker
  File "/home/seann/mcedit_v2/src/mcedit2/widgets/blockpicker.py", line 12, in <module>
    from mcedit2.ui.widgets.block_picker_multiple import Ui_blockPickerMultiple
ImportError: No module named block_picker_multiple
seann@black-beast:~/mcedit_v2 $ 
```

**Comment by codewarrior0** [comment]
Because you're not running from a git checkout, the .ui files aren't autogenerated on run. You'll have to generate them yourself with `python src/mcedit2/util/gen_ui.py`

**Comment by EvilSupahFly** [comment]
Fixed, but new issue discovered after load. I'll open a new issue for that.

**Comment by stkAnon** [comment]
gen_up.py does not seem to work as of beta6 if not run from a git repository:

```
$ python src/mcedit2/util/gen_ui.py
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
