### ISSUE TITLE
MCE2 Crashes on World Load - linux x64

### ISSUE THREAD

**Issue by EvilSupahFly** [mcedit/mcedit2#241]
On the initial loading screen, when I attempt to load a world (in this case, "Debug Test World"), MCE2 throws the following exception:

```
MCEdit version: 5.0.6
Python version: 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]
Platform: linux2
System version: Linux-4.5.3-040503-generic-x86_64-with-Ubuntu-15.10-wily
Processor: x86_64

Obtained a GL context with this format:
Valid: True
Version: 1.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 3.0 Mesa 11.0.2 (3, 0)
GL_VENDOR: 'X.Org'
GL_RENDERER: 'Gallium 0.4 on AMD TURKS (DRM 2.43.0, LLVM 3.6.2)'

------

Unhandled Exception

Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/worldlist.py", line 366, in worldListItemClicked (self is a WorldListWidget)
    self.showWorld(filename)
  File "/home/seann/mcedit_v2/src/mcedit2/worldlist.py", line 392, in showWorld (self is a WorldListWidget)
    self.setWorldView(MinimapWorldView(dim))
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 192, in __init__ (self is a MinimapWorldView)
    self.setDimension(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 233, in setDimension (self is a MinimapWorldView)
    self.sceneGraph = self.createSceneGraph()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
    self.worldScene = self.createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
    scene = super(MinimapWorldView, self).createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
    return worldscene.WorldScene(self.dimension, self.textureAtlas, self.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 233, in __init__ (self is a WorldScene)(named None)
    self.playersNode = PlayersNode(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 134, in __init__ (self is a PlayersNode)(named None)
    playerNodes.append(PlayerNode(player))
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 36, in __init__ (self is a PlayerNode)(named None)
    PlayerDataCache.getPlayerInfo(playerRef.UUID, _callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 151, in getPlayerInfo  
    PlayerDataCache.instance._getPlayerInfo(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 175, in _getPlayerInfo (self is a PlayerDataCache)
    self._queryServer(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 58, in _queryServer (self is a PlayerDataCache)
    assert isinstance(uuid, UUID)
AssertionError
```
The program doesn't actually stop however, and allows me to attempt to load the world anyway, then throws this:
```
An error occurred while opening /home/seann/.minecraft/saves/Debug Test World


Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 699, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 484, in __init__ (self is a EditorSession)
    self.editorTab = EditorTab(self)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 1408, in __init__ (self is a EditorTab)
    self.miniMap = MinimapWorldView(editorSession.currentDimension, editorSession.textureAtlas, editorSession.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 192, in __init__ (self is a MinimapWorldView)
    self.setDimension(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 233, in setDimension (self is a MinimapWorldView)
    self.sceneGraph = self.createSceneGraph()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
    self.worldScene = self.createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
    scene = super(MinimapWorldView, self).createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
    return worldscene.WorldScene(self.dimension, self.textureAtlas, self.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 233, in __init__ (self is a WorldScene)(named None)
    self.playersNode = PlayersNode(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 134, in __init__ (self is a PlayersNode)(named None)
    playerNodes.append(PlayerNode(player))
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 36, in __init__ (self is a PlayerNode)(named None)
    PlayerDataCache.getPlayerInfo(playerRef.UUID, _callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 151, in getPlayerInfo  
    PlayerDataCache.instance._getPlayerInfo(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 175, in _getPlayerInfo (self is a PlayerDataCache)
    self._queryServer(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 58, in _queryServer (self is a PlayerDataCache)
    assert isinstance(uuid, UUID)
AssertionError
```

In the terminal window, there's this:
```
seann@black-beast:~/mcedit_v2 $ mcedit2
fatal: No names found, cannot describe anything.
Logging level set
Logging to /home/seann/mcedit_v2/MCEdit User Data/mcedit.log
Setting up console handler
[WARNING][editorapp.py:91]:UserFilesDirectory: /home/seann/mcedit_v2/MCEdit User Data
[WARNING][configure_blocks.py:121]:Failed to read definitions file defined_blocks.json
[ERROR][player_server.py:83]:Error reading JSON from session server.
Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 81, in _queryFinished (self is a PlayerDataCache)
    jsonData = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads  
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode (self is a JSONDecoder)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode (self is a JSONDecoder)
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[ERROR][main.py:195]:Unhandled Exception: 
	
Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/worldlist.py", line 366, in worldListItemClicked (self is a WorldListWidget)
    self.showWorld(filename)
  File "/home/seann/mcedit_v2/src/mcedit2/worldlist.py", line 392, in showWorld (self is a WorldListWidget)
    self.setWorldView(MinimapWorldView(dim))
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 192, in __init__ (self is a MinimapWorldView)
    self.setDimension(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 233, in setDimension (self is a MinimapWorldView)
    self.sceneGraph = self.createSceneGraph()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
    self.worldScene = self.createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
    scene = super(MinimapWorldView, self).createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
    return worldscene.WorldScene(self.dimension, self.textureAtlas, self.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 233, in __init__ (self is a WorldScene)
    self.playersNode = PlayersNode(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 134, in __init__ (self is a PlayersNode)
    playerNodes.append(PlayerNode(player))
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 36, in __init__ (self is a PlayerNode)
    PlayerDataCache.getPlayerInfo(playerRef.UUID, _callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 151, in getPlayerInfo  
    PlayerDataCache.instance._getPlayerInfo(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 175, in _getPlayerInfo (self is a PlayerDataCache)
    self._queryServer(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 58, in _queryServer (self is a PlayerDataCache)
    assert isinstance(uuid, UUID)
AssertionError
[WARNING][editorsession.py:696]:'variants' key not found in states file fire, trying 1.8...
[WARNING][editorsession.py:696]:'variants' key not found in states file fire, skipping...

[... etc]

[ ... There's literally over ten thousand lines of these warnings ... ]

[WARNING][editorsession.py:696]:'variants' key not found in states file acacia_fence, trying 1.8...
[WARNING][editorsession.py:696]:'variants' key not found in states file acacia_fence, skipping...
[ERROR][editorapp.py:710]:EditorSession failed to open /home/seann/.minecraft/saves/Debug Test World: AssertionError()
Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 699, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 484, in __init__ (self is a EditorSession)
    self.editorTab = EditorTab(self)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 1408, in __init__ (self is a EditorTab)
    self.miniMap = MinimapWorldView(editorSession.currentDimension, editorSession.textureAtlas, editorSession.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 192, in __init__ (self is a MinimapWorldView)
    self.setDimension(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 233, in setDimension (self is a MinimapWorldView)
    self.sceneGraph = self.createSceneGraph()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
    self.worldScene = self.createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
    scene = super(MinimapWorldView, self).createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
    return worldscene.WorldScene(self.dimension, self.textureAtlas, self.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 233, in __init__ (self is a WorldScene)
    self.playersNode = PlayersNode(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 134, in __init__ (self is a PlayersNode)
    playerNodes.append(PlayerNode(player))
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 36, in __init__ (self is a PlayerNode)
    PlayerDataCache.getPlayerInfo(playerRef.UUID, _callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 151, in getPlayerInfo  
    PlayerDataCache.instance._getPlayerInfo(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 175, in _getPlayerInfo (self is a PlayerDataCache)
    self._queryServer(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 58, in _queryServer (self is a PlayerDataCache)
    assert isinstance(uuid, UUID)
AssertionError
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
Exception RuntimeError: 'Internal C++ object (PySide.QtCore.QTimer) already deleted.' in <bound method SelectionScene.__del__ of SelectionScene(None, visible=True, children=1, states=[<mcedit2.rendering.selection.CullFace object at 0x7f5fe2e00c90>, <mcedit2.rendering.renderstates._RenderstateAlphaBlend object at 0x7f5fe2e00cd0>])> ignored
seann@black-beast:~/mcedit_v2 $ 
```

Initially, I didn't wait for the "preview" to finish loading from the first world in the list before selecting a new one. So I relaunched MCE2, waited for the previe to complete this time, THEN chose a different world, but it still throws the second exception:
```
An error occurred while opening /home/seann/.minecraft/saves/Debug Test World/level.dat


Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 699, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 484, in __init__ (self is a EditorSession)
    self.editorTab = EditorTab(self)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 1408, in __init__ (self is a EditorTab)
    self.miniMap = MinimapWorldView(editorSession.currentDimension, editorSession.textureAtlas, editorSession.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 192, in __init__ (self is a MinimapWorldView)
    self.setDimension(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 233, in setDimension (self is a MinimapWorldView)
    self.sceneGraph = self.createSceneGraph()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
    self.worldScene = self.createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
    scene = super(MinimapWorldView, self).createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
    return worldscene.WorldScene(self.dimension, self.textureAtlas, self.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 233, in __init__ (self is a WorldScene)(named None)
    self.playersNode = PlayersNode(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 134, in __init__ (self is a PlayersNode)(named None)
    playerNodes.append(PlayerNode(player))
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 36, in __init__ (self is a PlayerNode)(named None)
    PlayerDataCache.getPlayerInfo(playerRef.UUID, _callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 151, in getPlayerInfo  
    PlayerDataCache.instance._getPlayerInfo(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 175, in _getPlayerInfo (self is a PlayerDataCache)
    self._queryServer(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 58, in _queryServer (self is a PlayerDataCache)
    assert isinstance(uuid, UUID)
AssertionError
```

The world in question - "Debug Test World" - was created with Minecraft version 1.10. So I tried again with an older world from 1.9.4, but that didn't load either:
```
An error occurred while opening /home/seann/.minecraft/saves/1_9_4 Debug Test World/level.dat


Traceback (most recent call last):
  File "/home/seann/mcedit_v2/src/mcedit2/editorapp.py", line 699, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 484, in __init__ (self is a EditorSession)
    self.editorTab = EditorTab(self)
  File "/home/seann/mcedit_v2/src/mcedit2/editorsession.py", line 1408, in __init__ (self is a EditorTab)
    self.miniMap = MinimapWorldView(editorSession.currentDimension, editorSession.textureAtlas, editorSession.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 192, in __init__ (self is a MinimapWorldView)
    self.setDimension(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 233, in setDimension (self is a MinimapWorldView)
    self.sceneGraph = self.createSceneGraph()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
    self.worldScene = self.createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
    scene = super(MinimapWorldView, self).createWorldScene()
  File "/home/seann/mcedit_v2/src/mcedit2/worldview/worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
    return worldscene.WorldScene(self.dimension, self.textureAtlas, self.geometryCache)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/worldscene.py", line 233, in __init__ (self is a WorldScene)(named None)
    self.playersNode = PlayersNode(dimension)
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 134, in __init__ (self is a PlayersNode)(named None)
    playerNodes.append(PlayerNode(player))
  File "/home/seann/mcedit_v2/src/mcedit2/rendering/players.py", line 36, in __init__ (self is a PlayerNode)(named None)
    PlayerDataCache.getPlayerInfo(playerRef.UUID, _callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 151, in getPlayerInfo  
    PlayerDataCache.instance._getPlayerInfo(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 175, in _getPlayerInfo (self is a PlayerDataCache)
    self._queryServer(uuid, callback)
  File "/home/seann/mcedit_v2/src/mcedit2/util/player_server.py", line 58, in _queryServer (self is a PlayerDataCache)
    assert isinstance(uuid, UUID)
AssertionError
```

Am I doing something wrong or am I just really unlucky?

**Comment by codewarrior0** [comment]
All I can figure out from that trace is you have playerdata files that have no UUID tags, which means they are from 1.6 or earlier. I've added a guard against that in 448eab0e0c36aa0acd9558f185af3a58ce5457e4 - do a `git pull` and see if that's fixed.

**Comment by EvilSupahFly** [comment]
1.6? That's odd. I used MCE Unified to generate the world originally.

**Comment by EvilSupahFly** [comment]
No more crashes on start-up or world load. :-)

**Comment by Paradox** [comment]
I see this is closed, but, is this fix in beta 6, available for download? I ask, because, I seem to be having this same issue.
