### ISSUE TITLE
MCEdit 2 - 1071 not recognizing Forge Installation

### ISSUE THREAD

**Issue by Mattrock607** [mcedit/mcedit2#250]
I can't get MCEdit to recognize Forge. It lists only 1.10.2 and 1.7.10 under "versions." As a result, all mod blocks show up as unknown items on all maps; only vanilla objects are appearing. I haven't been able to find any guides that explain whether or not I've installed it properly, and I haven't found anything about getting MCEdit to recognize Forge and its mods. When I ignore that and try to load a world regardless of the error, I get the following:

```
An error occurred while opening C:\Users\Matt\AppData\Roaming\.minecraft\saves\Test World 
'NoneType' object has no attribute 'startswith'

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 699, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 384, in __init__ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 692, in setConfiguredBlocks (self is a EditorSession)
  File "mcedit2\editorsession.py", line 696, in reloadModels (self is a EditorSession)
  File "mcedit2\rendering\blockmodels.pyx", line 235, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:5182)  
    self.loadModel(block, resourcePath, resourceVariant, modelDict, variantXrot, variantYrot)
  File "mcedit2\rendering\blockmodels.pyx", line 338, in mcedit2.rendering.blockmodels.BlockModels.loadModel (src/mcedit2/rendering/blockmodels.c:6875)  
    while v.startswith("#"):
AttributeError: 'NoneType' object has no attribute 'startswith'


```
When I click "Configure blocks & Items" under "options," I get the following crash report:

MCEdit version: 2.0.0alpha-1071
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.10586
Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.13416 Compatibility Profile Context 15.300.1025.1001 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon R9 200 Series'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 926, in showConfigureBlocksDialog (self is a MCEditApp)
  File "mcedit2\dialogs\configure_blocks.py", line 442, in showWithSession (self is a ConfigureBlocksDialog)
AttributeError: 'NoneType' object has no attribute 'unknownBlocks'

Here's information about my machine, my OS, etc.:

OS: Windows 10
CPU: AMD FX-8370
RAM: 16 GB (6 GB allocated to Minecraft)
MC Version: 1.7.10, Forge 1.7.10-1558
MCEdit Version: 2.0 build 1071

I'll try to install an older version of MCEdit and see if that helps. I don't really know what else to do at this point :/

**Comment by codewarrior0** [comment]
Fixed.

FYI, all mod blocks will show up as unknown blocks until they are configured.

**Comment by pathcat** [comment]
Hi there,
I am having the same problem. I am using mcedit 2.0.0-beta7. do i need to update? how do i do that?
-cat
