### ISSUE TITLE
Freeze/Crash Shortly After Loading World

### ISSUE THREAD

**Issue by Gaveno** [mcedit/mcedit2#251]
I've tried the 64 and 32 bit version of MCEdit 2.0 alpha 1071 and shortly after the world is loaded I get these errors in my console and MCEdit's GUI completely freezes.

It doesn't seem to matter if the world is from 1.8.9, or 1.10.2, modded, or vanilla, the crash still happens.

Sometimes just before the crash happens, the entire world will briefly turn into purple meshes.

```
[ERROR][__init__.py:1193]:Rendering chunk (14, 15) failed: KeyError((u'minecraft:fence', ('east=false', 'north=true', 'south=false', 'west=false')),)
Traceback (most recent call last):
  File "mcedit2\rendering\worldscene.py", line 114, in workOnChunk (self is a SceneUpdateTask)
  File "mcedit2\util\profiler.py", line 87, in iterate (self is a Profiler)
  File "mcedit2\rendering\chunkupdate.py", line 159, in __iter__ (self is a ChunkUpdate)
  File "mcedit2\util\profiler.py", line 87, in iterate (self is a Profiler)
  File "mcedit2\rendering\chunkupdate.py", line 224, in buildSectionMeshes (self is a ChunkUpdate)
  File "mcedit2\util\profiler.py", line 87, in iterate (self is a Profiler)
  File "mcedit2\rendering\chunkupdate.py", line 492, in __iter__ (self is a SectionUpdate)
  File "mcedit2\rendering\modelmesh.pyx", line 369, in mcedit2.rendering.modelmesh.BlockModelMesh.createVertexArrays (src/mcedit2/rendering/modelmesh.c:7247)
    quadListObj = blockModels.cookedModelsByBlockState[actualState]
KeyError: (u'minecraft:fence', ('east=false', 'north=true', 'south=false', 'west=false'))
[ERROR][__init__.py:1193]:Rendering chunk (17, 10) failed: KeyError(('minecraft:redstone_wire', (u'east=none', u'north=none', u'power=0', u'south=side', u'west=none')),)
Traceback (most recent call last):
  File "mcedit2\rendering\worldscene.py", line 114, in workOnChunk (self is a SceneUpdateTask)
  File "mcedit2\util\profiler.py", line 87, in iterate (self is a Profiler)
  File "mcedit2\rendering\chunkupdate.py", line 159, in __iter__ (self is a ChunkUpdate)
  File "mcedit2\util\profiler.py", line 87, in iterate (self is a Profiler)
  File "mcedit2\rendering\chunkupdate.py", line 224, in buildSectionMeshes (self is a ChunkUpdate)
  File "mcedit2\util\profiler.py", line 87, in iterate (self is a Profiler)
  File "mcedit2\rendering\chunkupdate.py", line 492, in __iter__ (self is a SectionUpdate)
  File "mcedit2\rendering\modelmesh.pyx", line 369, in mcedit2.rendering.modelmesh.BlockModelMesh.createVertexArrays (src/mcedit2/rendering/modelmesh.c:7247)
    quadListObj = blockModels.cookedModelsByBlockState[actualState]
KeyError: ('minecraft:redstone_wire', (u'east=none', u'north=none', u'power=0', u'south=side', u'west=none'))
```

**Comment by codewarrior0** [comment]
Fixed in beta3.
