### ISSUE TITLE
chucks won't load therefore McEdit crashes 

### ISSUE THREAD

**Issue by 5h4dow** [mcedit/mcedit2#253]
this is what it tells me any help

MCEdit version: 2.0.0alpha-1071
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8.1-6.3.9600
Processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.3.0 - Build 10.18.10.3960 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 5500'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\command.py", line 27, in redo (self is a BrushCommand)
  File "mcedit2\editortools\brush\__init__.py", line 70, in perform (self is a BrushCommand)
  File "mceditlib\util\__init__.py", line 29, in exhaust  
  File "mcedit2\editortools\brush\__init__.py", line 78, in _perform (self is a BrushCommand)
  File "mceditlib\operations\__init__.py", line 36, in next (self is a FillBlocksOperation)
  File "mceditlib\operations\block_fill.py", line 137, in operateOnChunk (self is a FillBlocksOperation)
AttributeError: 'str' object has no attribute 'ID'

**Comment by codewarrior0** [comment]
Can't reproduce
