### ISSUE TITLE
MCEdit has an error when saving a schematic

### ISSUE THREAD

**Issue by Thisisthebest** [mcedit/mcedit2#271]
I saw this:

MCEdit version: 2.0.0alpha-1018
Python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.4
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.4.0 - Build 20.19.15.4300 (4, 4)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 530'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 899, in export (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 822, in exportSchematicIter (self is a WorldEditorDimension)
  File "mceditlib\schematic.py", line 45, in createSchematic  
  File "mceditlib\schematic.py", line 210, in __init__ (self is a SchematicFileAdapter)
ValueError: negative dimensions are not allowed

Please tell me what happened!

**Comment by codewarrior0** [comment]
You somehow selected an area with negative length, width, or height, I'm pretty sure this has been fixed.
