### ISSUE TITLE
UnicodeDecodeError - MCEdit 2.0.0 Beta 6

### ISSUE THREAD

**Issue by BunnyWarlord** [mcedit/mcedit2#304]
An error occurred while opening C:/Users/User/AppData/Roaming/.minecraft/saves/The Halberd/level.dat
'utf8' codec can't decode byte 0xc0 in position 16: invalid start byte

Traceback (most recent call last):
File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
File "mcedit2\editorsession.py", line 201, in init (self is a EditorSession)
File "mceditlib\worldeditor.py", line 233, in init (self is a WorldEditor)
File "mceditlib\findadapter.py", line 62, in findAdapter
File "mceditlib\anvil\adapter.py", line 463, in init (self is a AnvilWorldAdapter)
File "mceditlib\anvil\adapter.py", line 530, in loadMetadata (self is a AnvilWorldAdapter)
File "src\mceditlib\nbt.pyx", line 569, in mceditlib.nbt.load (src/mceditlib/nbt.c:12098)
File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)
File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)
File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)
File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)
File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)
File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)
File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)
File "src\mceditlib\nbt.pyx", line 668, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13041)
File "src\mceditlib\nbt.pyx", line 709, in mceditlib.nbt.load_name (src/mceditlib/nbt.c:13470)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 16: invalid start byte

This happens every time I try starting MC Edit. Workarounds?

**Comment by xZeroMCPE** [comment]
Ah I see, 

Which MC version was the world created in? any special creatures in there?

**Comment by BunnyWarlord** [comment]
1.10.2 I think. I don't think there were any special mobs except a donkey, but I got rid of it. There's also an ender crystal. It's battleship halberd from kirby super star, so the crystal is the reactor core.

**Comment by codewarrior0** [comment]
Could you upload the `level.dat` from that world? It's the only file I need, since it's the one that presents the error.

**Comment by BunnyWarlord** [comment]
Here's the dat file of the level: https://www.dropbox.com/s/uip8ya4lrc8e4je/level.dat?dl=0

**Comment by codewarrior0** [comment]
Thanks! Looks like your dat file is mildly damaged, but in a way that does not affect Minecraft at all. 

There's an extra `gameRule` with an invalid name that contains trailing NULL characters, and since Java's UTF-8 encodes NULL characters differently than the UTF-8 standard says (see "Modified UTF-8"), Python's UTF-8 encoder fails on the byte sequence `0xC0 0x80` which should decode to a NULL character (`U+0000`).

Your workaround is to open the level.dat in [NBTExplorer](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac), navigate to `level.dat > Data > GameRules` and delete the tag named `disableElytraMov<><><><><><><><>`.

**Comment by BunnyWarlord** [comment]
It looks like the world loaded as intended. Thanks a bunch! Feels great knowing I won't have to rebuild that giant airship from scratch.
