### ISSUE TITLE
build under ubuntu fails

### ISSUE THREAD

**Issue by NESC1US** [mcedit/mcedit2#312]
commit 56cd05fea0291aa2287edbea07a9eb3a777e7519
most recent version of ubuntu 16.04.2
minecraft version does not even apply here

blabla@somwhere ~/mcedit2-master$ python setup_mcedit2.py build
Traceback (most recent call last):
  File "setup_mcedit2.py", line 28, in <module>
    "src/mcedit2/rendering/modelmesh.pyx",
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 818, in cythonize
    aliases=aliases)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 719, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 590, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 600, in transitive_merge
    node, extract, merge, seen, {}, self.cimported_files)[0]
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 611, in transitive_merge_helper
    for next in outgoing(node):
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
    res = cache[args] = f(self, *args)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 539, in cimported_files
    pxd_file = self.find_pxd(module, filename)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
    res = cache[args] = f(self, *args)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 523, in find_pxd
    pxd = self.context.find_pxd_file(relative, None)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 239, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=sys_path)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 280, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Utils.py", line 30, in wrapper
    res = cache[args] = f(*args)
  File "/home/blabla/.local/lib/python2.7/site-packages/Cython/Utils.py", line 148, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 17: ordinal not in range(128)

SAME HAPPENS WITH SYSTEM packages

$ rm ~/.local/lib/python2.7/site-packages/ -rf
blabla@somwhere ~/mcedit2-master$ python setup_mcedit2.py build
Traceback (most recent call last):
  File "setup_mcedit2.py", line 28, in <module>
    "src/mcedit2/rendering/modelmesh.pyx",
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 758, in cythonize
    aliases=aliases)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 664, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 564, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 574, in transitive_merge
    node, extract, merge, seen, {}, self.cimported_files)[0]
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 585, in transitive_merge_helper
    for next in outgoing(node):
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 43, in wrapper
    res = cache[args] = f(self, *args)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 513, in cimported_files
    pxd_file = self.find_pxd(module, filename)
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 43, in wrapper
    res = cache[args] = f(self, *args)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 497, in find_pxd
    pxd = self.context.find_pxd_file(relative, None)
  File "/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 239, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=sys_path)
  File "/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 280, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 29, in wrapper
    res = cache[args] = f(*args)
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 119, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 17: ordinal not in range(128)

**Comment by NESC1US** [comment]
I was being idiot here, the path contained non-ascii character so python 2.7 died when playing with posixpath.py, realising that, I moved it elsewhere and it works
