### ISSUE TITLE
Issue trying to delete broken Entity caused by Tinker's Construct in Project Ozone 2

### ISSUE THREAD

**Issue by Mitsunee** [mcedit/mcedit2#316]
`MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 378.66 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 970/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\widgets\inspector\__init__.py", line 267, in removeEntity (self is a InspectorWidget)
  File "mceditlib\worldeditor.py", line 83, in remove (self is a EntityListProxy)
  File "_abcoll.py", line 689, in remove (self is a TAG_List)(named Entities)
  File "_abcoll.py", line 628, in index (self is a TAG_List)(named Entities)
ValueError
`
Game crash caused by the entity: https://pastebin.com/eLFYw3xB
What happend: I tried to shoot a Spectre Ghost, missed, and probably managed to hit myself. I downloaded the 64bit version of beta7, found the entity of the bolt and got this error.

**Comment by Mitsunee** [comment]
update: clicked restart, got more fun stuff:
`An error occurred while opening D:\Downloads\mceditmemers\mcedit2-win64-2.0.0-beta7\mcedit2.exe
Cannot detect type of file D:\Downloads\mceditmemers\mcedit2-win64-2.0.0-beta7\mcedit2.exe.

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 182, in __init__ (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 233, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 66, in findAdapter  
UnknownFormatError: Cannot detect type of file D:\Downloads\mceditmemers\mcedit2-win64-2.0.0-beta7\mcedit2.exe.
`

**Comment by codewarrior0** [comment]
First traceback: you didn't mention that you clicked "Delete Entity" twice.

Second traceback: fixed in 34fa322c92f07083f4a121cc53f4bfd48d25fc09
