### ISSUE TITLE
MCEdit 2.0.0 Beta 7 - Invalid Start Byte

### ISSUE THREAD

**Issue by BunnyWarlord** [mcedit/mcedit2#324]
So I can't open MCEdit; instead it gives me this:

MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.14393
Processor: Intel64 Family 6 Model 23 Stepping 6, GenuineIntel

Unhandled Exception

Traceback (most recent call last):
File "mcedit2\worldlist.py", line 464, in showEvent (self is a WorldListWidget)
File "mcedit2\worldlist.py", line 382, in showWorld (self is a WorldListWidget)
File "mceditlib\worldeditor.py", line 233, in init (self is a WorldEditor)
File "mceditlib\findadapter.py", line 62, in findAdapter
File "mceditlib\anvil\adapter.py", line 463, in init (self is a AnvilWorldAdapter)
File "mceditlib\anvil\adapter.py", line 530, in loadMetadata (self is a AnvilWorldAdapter)
File "src\mceditlib\nbt.pyx", line 590, in mceditlib.nbt.load (src/mceditlib/nbt.c:12716)
File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:13614)
File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13691)
File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14856)
File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:13614)
File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13691)
File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14856)
File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:13614)
File "src\mceditlib\nbt.pyx", line 689, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13679)
File "src\mceditlib\nbt.pyx", line 733, in mceditlib.nbt.load_name (src/mceditlib/nbt.c:14066)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 16: invalid start byte

I'm no expert at programming, but the one thing I see out of place is that it says "Platform: win32". I don't know what it's trying to get at here, because I know I downloaded the 64 bit version, and my computer is 64 bit. What am I missing here?

**Comment by codewarrior0** [comment]
Fixed
