### ISSUE TITLE
Cant use schematics

### ISSUE THREAD

**Issue by Swaki** [mcedit/mcedit2#332]
So i tried to get a part of a multiplayer server and when i tried to load the schematic and confirm it this happend. 

MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.15063
Processor: AMD64 Family 21 Model 48 Stepping 1, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.13474 Compatibility Profile Context 22.19.165.1 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'Radeon (TM) RX 470 Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editortools\move.py", line 244, in confirmImport (self is a MoveTool)(named Move)
  File "contextlib.py", line 17, in __enter__ (self is a GeneratorContextManager)
  File "mcedit2\command.py", line 59, in begin (self is a MoveFinishCommand)
  File "mcedit2\editorsession.py", line 1189, in beginUndo (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 299, in beginUndo (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 707, in createRevision (self is a AnvilWorldAdapter)
AttributeError: 'AnvilWorldFolder' object has no attribute 'createRevision'

**Comment by codewarrior0** [comment]
Looks like you opened the world by clicking the "View" button, so it's in read-only mode. I'll make it fail more gracefully, but you will still need to click "Edit" if you want to actually edit the world.
