### ISSUE TITLE
MCEdit 2.0.0-beta7 not starting

### ISSUE THREAD

**Issue by DrRayThe2nd** [mcedit/mcedit2#333]
After installing and running MCEdit2, I receive this console output:

```user@computer:~/Desktop/mcedit2$ sudo mcedit2
Logging level set
Logging to /root/.mcedit2/mcedit2.log
Setting up console handler
[WARNING][editorapp.py:95]:UserFilesDirectory: /root/.mcedit2
[ERROR][main.py:203]:Unhandled Exception: 
	Could not get resource path for mcedit2/i18n
(Tried /usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/i18n which does not exist)
Traceback (most recent call last):
  File "/usr/local/bin/mcedit2", line 11, in <module>  
    load_entry_point('mcedit2==2.0.0a1.dev0', 'console_scripts', 'mcedit2')()
  File "/usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/main.py", line 222, in main  
    app = startup()
  File "/usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/main.py", line 193, in startup  
    editorApp = MCEditApp(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/editorapp.py", line 99, in __init__ (self is a MCEditApp)
    self.transDir = resourcePath('mcedit2/i18n')
  File "/usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/util/resources.py", line 74, in resourcePath  
    raise RuntimeError("Could not get resource path for %s\n(Tried %s which does not exist)" % (filename, path))
RuntimeError: Could not get resource path for mcedit2/i18n
(Tried /usr/local/lib/python2.7/dist-packages/mcedit2-2.0.0a1.dev0-py2.7-linux-x86_64.egg/mcedit2/i18n which does not exist)
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

Please help!

**Comment by codewarrior0** [comment]
Looks like you didn't follow the install instructions. Use `setup.py develop`, not `install`
