### ISSUE TITLE
Can't open MCEdit 2 on my PC.

### ISSUE THREAD

**Issue by hoodhoodihopman** [mcedit/mcedit2#338]
I'm trying to merge two worlds on MCEdit 2.0.0 Beta 7. Unfortunately, when I open one of the worlds I am greeted with this error:

An error occurred while opening C:/Users/Rob/Desktop/HaljalikaServer (Hal)-2/level.dat
Failed to read PNG file C:\Users\Rob\Desktop\mcedit2-win64-2.0.0-beta7\MCEdit 2 Files\player_data\skins\0701fdfbd8b94ac98c01657868121ec4.png

Traceback (most recent call last):
File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
File "mcedit2\editorsession.py", line 515, in init (self is a EditorSession)
File "mcedit2\editorsession.py", line 1439, in init (self is a EditorTab)
File "mcedit2\worldview\minimap.py", line 152, in init (self is a MinimapWorldView)
File "mcedit2\worldview\worldview.py", line 192, in init (self is a MinimapWorldView)
File "mcedit2\worldview\worldview.py", line 233, in setDimension (self is a MinimapWorldView)
File "mcedit2\worldview\worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
File "mcedit2\worldview\minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
File "mcedit2\worldview\worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
File "mcedit2\rendering\worldscene.py", line 235, in init (self is a WorldScene)(named None)
File "mcedit2\rendering\players.py", line 141, in init (self is a PlayersNode)(named None)
File "mcedit2\rendering\players.py", line 37, in init (self is a PlayerNode)(named None)
File "mcedit2\util\player_server.py", line 153, in getPlayerInfo
File "mcedit2\util\player_server.py", line 190, in _getPlayerInfo (self is a PlayerDataCache)
File "mcedit2\rendering\players.py", line 31, in _callback (self is a PlayerNode)(named None)
File "mcedit2\rendering\players.py", line 50, in texturePath (self is a PlayerNode)(named None)
File "mcedit2\util\load_png.py", line 49, in loadPNGFile
IOError: Failed to read PNG file C:\Users\Rob\Desktop\mcedit2-win64-2.0.0-beta7\MCEdit 2 Files\player_data\skins\0701fdfbd8b94ac98c01657868121ec4.png

Any ideas?

**Comment by codewarrior0** [comment]
Fixed
