### ISSUE TITLE
MCEdit 2 Error on generate vilage.

### ISSUE THREAD

**Issue by Rambo99** [mcedit/mcedit2#339]
MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 382.05 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 980/PCIe/SSE2'

Unhandled Exception

Traceback (most recent call last):
File "mcedit2\editortools\generate.py", line 429, in generateClicked (self is a GenerateTool)(named Generate)
File "mcedit2\editortools\generate.py", line 66, in generate (self is a CityGeneratePlugin)
File "mcedit2\synth\l_system_plugin.py", line 98, in generateInSchematic (self is a CityGeneratePlugin)
File "mcedit2\synth\l_system_plugin.py", line 78, in createSymbolList (self is a CityGeneratePlugin)
File "mcedit2\util\showprogress.py", line 77, in showProgress
File "mceditlib\util\progress.py", line 26, in rescaleProgress
File "mcedit2\synth\l_system_plugin.py", line 73, in process
File "mcedit2\synth\l_system.py", line 133, in applyReplacementsIterated
TypeError: range() integer end argument expected, got float.

**Comment by ScorchStorm** [comment]
I keep getting the same problem, which happens most of the time I try to use a plugin in MCedit 2.0
