### ISSUE TITLE
An error occurred while reading the file. This file might not be a Minecraft world. [utf8] 

### ISSUE THREAD

**Issue by Zackpow** [mcedit/mcedit2#346]
An error occurred while reading the file C:\Users\zackp\Saved Games\Minecraft Server\world\level.dat. This file might not be a Minecraft world. If it is, please file a bug report.
'utf8' codec can't decode byte 0xc0 in position 1: invalid start byte

Traceback (most recent call last):
  File "mcedit2\worldlist.py", line 387, in showWorld (self is a WorldListWidget)
  File "mceditlib\worldeditor.py", line 233, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 62, in findAdapter  
  File "mceditlib\anvil\adapter.py", line 463, in __init__ (self is a AnvilWorldAdapter)
  File "mceditlib\anvil\adapter.py", line 530, in loadMetadata (self is a AnvilWorldAdapter)
  File "src\mceditlib\nbt.pyx", line 590, in mceditlib.nbt.load (src/mceditlib/nbt.c:12716)  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:13614)  
  File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13691)  
  File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14856)  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:13614)  
  File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13691)  
  File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14856)  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:13614)  
  File "src\mceditlib\nbt.pyx", line 689, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13679)  
  File "src\mceditlib\nbt.pyx", line 733, in mceditlib.nbt.load_name (src/mceditlib/nbt.c:14066)  
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 1: invalid start byte

**Comment by codewarrior0** [comment]
#324
