### ISSUE TITLE
crashing when starting mcedit2

### ISSUE THREAD

**Issue by shedowtnt** [mcedit/mcedit2#349]
error log:MCEdit version: 2.0.0-beta10
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 23 Stepping 10, GenuineIntel

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'

steps to reproduce: click mcedit2
mcedit version number: mcedit 2 64bits beta 10
minecraft version number: none
operating system version: windowns 7 home premium 64 bits

**Comment by codewarrior0** [comment]
Language?

**Comment by shedowtnt** [comment]
portuguese

**Comment by codewarrior0** [comment]
Fixed.

**Comment by shedowtnt** [comment]
what
