### ISSUE TITLE
An error occurred while reading the file - 'utf8' codec can't decode byte 0xc0 in position 1: invalid start byte [2.0.0-beta11]

### ISSUE THREAD

**Issue by Zackpow** [mcedit/mcedit2#352]
[2.0.0-beta11]

An error occurred while reading the file C:\Users\zackp\Saved Games\Minecraft Server\world\level.dat. This file might not be a Minecraft world. If it is, please file a bug report.
'utf8' codec can't decode byte 0xc0 in position 1: invalid start byte

Traceback (most recent call last):
  File "mcedit2\worldlist.py", line 387, in showWorld (self is a WorldListWidget)
  File "mceditlib\worldeditor.py", line 233, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 62, in findAdapter  
  File "mceditlib\anvil\adapter.py", line 463, in __init__ (self is a AnvilWorldAdapter)
  File "mceditlib\anvil\adapter.py", line 530, in loadMetadata (self is a AnvilWorldAdapter)
  File "src\mceditlib\nbt.pyx", line 590, in mceditlib.nbt.load  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound  
  File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named  
  File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound  
  File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named  
  File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound  
  File "src\mceditlib\nbt.pyx", line 689, in mceditlib.nbt.load_named  
  File "src\mceditlib\nbt.pyx", line 733, in mceditlib.nbt.load_name  
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 1: invalid start byte

**Comment by codewarrior0** [comment]
#304
