### ISSUE TITLE
Cant access my world

### ISSUE THREAD

**Issue by RPEHES** [mcedit/mcedit2#357]
I have a error opening my world pls help here is the error:  
MCEdit version: 2.0.0alpha-823
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10.0.14393
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.0.0 - Build 10.18.10.4358 (4, 0)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.editorapp", line 747, in editWorldFromList (self is a MCEditApp)
  File "out00-PYZ.pyz\mcedit2.editorapp", line 698, in loadFile (self is a MCEditApp)
  File "out00-PYZ.pyz\mcedit2.editorsession", line 315, in __init__ (self is a EditorSession)
  File "out00-PYZ.pyz\mcedit2.editorsession", line 614, in setConfiguredBlocks (self is a EditorSession)
  File "out00-PYZ.pyz\mcedit2.editorsession", line 618, in reloadModels (self is a EditorSession)
  File "mcedit2\rendering\blockmodels.pyx", line 224, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:4878)  
    result = self.loadResourceVariant(resourcePath, resourceVariant)
  File "mcedit2\rendering\blockmodels.pyx", line 410, in mcedit2.rendering.blockmodels.BlockModels.loadResourceVariant (src/mcedit2/rendering/blockmodels.c:7653)  
    variantDict = variants[resourceVariant]
KeyError: u'attached=false,facing=south,powered=false,suspended=false

**Comment by codewarrior0** [comment]
Old version. Get the newest one from http://www.mcedit.net/
