### ISSUE TITLE
Error: Can't start MCEdit at all, Unhandled Exception

### ISSUE THREAD

**Issue by PotatoPvP** [mcedit/mcedit2#374]
I can't start MCEdit 64bit 2.0.0-beta 11 at all. Today I started MCEdit as usual but the error popped up. I have tried the 32bit version and other versions but none of them work. I'm using Windows 7 Professional 64bit.

mcedit log  https://pastebin.com/HsCuCUVj

An Error Has Occurred: Unhandled Exception
MCEdit version: 2.0.0-beta11
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 388.59 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 970/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\worldlist.py", line 481, in loadTimerFired (self is a WorldListWidget)
  File "mcedit2\rendering\chunkloader.py", line 205, in next (self is a ChunkLoader)
  File "mcedit2\rendering\chunkloader.py", line 244, in _loadChunks (self is a ChunkLoader)
  File "mcedit2\rendering\chunkloader.py", line 275, in _loadChunk (self is a ChunkLoader)
  File "mceditlib\worldeditor.py", line 814, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 898, in readChunk (self is a AnvilWorldAdapter)
  File "src\mceditlib\nbt.pyx", line 590, in mceditlib.nbt.load  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound  
  File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named  
  File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound  
  File "src\mceditlib\nbt.pyx", line 690, in mceditlib.nbt.load_named  
  File "src\mceditlib\nbt.pyx", line 804, in mceditlib.nbt.load_tag  
  File "src\mceditlib\nbt.pyx", line 705, in mceditlib.nbt.load_list  
  File "src\mceditlib\nbt.pyx", line 807, in mceditlib.nbt.load_tag  
  File "src\mceditlib\nbt.pyx", line 683, in mceditlib.nbt.load_compound  
  File "src\mceditlib\nbt.pyx", line 689, in mceditlib.nbt.load_named  
  File "src\mceditlib\nbt.pyx", line 733, in mceditlib.nbt.load_name  
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 1: invalid start byte

**Comment by codewarrior0** [comment]
Your save file is using the latest MC 1.13 snapshots

**Comment by minexew** [comment]
MCEdit still probably shouldn't shit the bed if it encounters a corrupted world (that the user didn't explicitly open), but removing the world is a sufficient workaround.
