### ISSUE TITLE
Cannot start MCEdit 2.0.0 Beta 11

### ISSUE THREAD

**Issue by As400** [mcedit/mcedit2#379]
I've been searching around but haven't found anything related.

I'm running on Windows 10 Home Edition, 64 bit, trying to run 64-bit version of MCEdit 2.0.0-beta11. The 32-bit version also crashes at startup.
The error is the following:
 
[INFO][main.py:177]:MCEdit2 version 2.0.0-beta11 starting...
[INFO][acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[INFO][settings.py:112]:Loading app settings from D:\Users\pmigu\Downloads\MCEdit\mcedit2-win64-2.0.0-beta11\MCEdit 2 Files\mcedit2.ini
[INFO][loadablechunks.py:17]:Making checkerboard texture...
[WARNING][editorapp.py:95]:UserFilesDirectory: D:\Users\pmigu\Downloads\MCEdit\mcedit2-win64-2.0.0-beta11\MCEdit 2 Files
[INFO][editorapp.py:120]:Loaded translator. Selected language: pt_PT
[INFO][editorapp.py:150]:Loaded stylesheet.
[ERROR][main.py:203]:Unhandled Exception: 
	u'vers\xe3o'
Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'
[ERROR][base.py:676]:Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
[ERROR][base.py:704]:[u"KeyError: u'vers\\xe3o'", u'  File "mcedit2\\main.py", line 226, in <module>', u'  File "mcedit2\\main.py", line 222, in main', u'  File "mcedit2\\util\\profiler.py", line 73, in _wrapper', u'  File "mcedit2\\main.py", line 193, in startup', u'  File "mcedit2\\editorapp.py", line 154, in __init__', u'  File "mcedit2\\editorapp.py", line 56, in __init__']

This stops the programs and just closes it.

**Comment by Polda18** [comment]
I extracted the self-extracting archive of 64bit version of MCEdit to C:\MCEdit\* and tried to run the mcedit2.exe inside the installation folder. Program doesn't start at all. This is console output:

    PyInstaller Bootloader 3.x
    LOADER: executable is C:\MCEdit\mcedit2-win64-2.0.0-beta11\mcedit2.exe
    LOADER: homepath is C:\MCEdit\mcedit2-win64-2.0.0-beta11
    LOADER: _MEIPASS2 is NULL
    LOADER: archivename is C:\MCEdit\mcedit2-win64-2.0.0-beta11\mcedit2.exe
    LOADER: Extracting binaries
    LOADER: Executing self as child
    LOADER: set _MEIPASS2 to C:\Users\nimrod\AppData\Local\Temp\_MEI61402
    LOADER: Setting up to run child
    LOADER: Creating child process
    LOADER: Waiting for child process to finish...
    PyInstaller Bootloader 3.x
    LOADER: executable is C:\MCEdit\mcedit2-win64-2.0.0-beta11\mcedit2.exe
    LOADER: homepath is C:\MCEdit\mcedit2-win64-2.0.0-beta11
    LOADER: _MEIPASS2 is C:\Users\nimrod\AppData\Local\Temp\_MEI61402
    LOADER: archivename is C:\MCEdit\mcedit2-win64-2.0.0-beta11\mcedit2.exe
    LOADER: SetDllDirectory(C:\Users\nimrod\AppData\Local\Temp\_MEI61402)
    LOADER: Already in the child - running user's code.
    LOADER: manifestpath: C:\Users\nimrod\AppData\Local\Temp\_MEI61402\mcedit2.exe.manifest
    LOADER: Activation context created
    LOADER: Activation context activated
    LOADER: Python library: C:\Users\nimrod\AppData\Local\Temp\_MEI61402\python27.dll
    LOADER: Loaded functions from Python library.
    LOADER: Manipulating environment (sys.path, sys.prefix)
    LOADER: sys.prefix is C:\Users\nimrod\AppData\Local\Temp\_MEI61~1
    LOADER: Setting runtime options
    LOADER: Bootloader option: pyi-windows-manifest-filename mcedit2.exe.manifest
    LOADER: Initializing python
    LOADER: Overriding Python's sys.path
    LOADER: Post-init sys.path is C:\Users\nimrod\AppData\Local\Temp\_MEI61402
    LOADER: Setting sys.argv
    LOADER: setting sys._MEIPASS
    LOADER: importing modules from CArchive
    LOADER: extracted struct
    LOADER: callfunction returned...
    LOADER: extracted pyimod01_os_path
    LOADER: callfunction returned...
    LOADER: extracted pyimod02_archive
    LOADER: callfunction returned...
    LOADER: extracted pyimod03_importers
    LOADER: callfunction returned...
    LOADER: Installing PYZ archive with Python modules.
    LOADER: PYZ archive: out00-PYZ.pyz
    LOADER: Running pyiboot01_bootstrap.py
    LOADER: Running pyi_rth_win32comgenpy.py
    LOADER: Running pyi_rth_pkgres.py
    LOADER: Running pyi_rth_traitlets.py
    LOADER: Running pyi_rth_qt4plugins.py
    LOADER: Running main.py
    Logging level set
    sys.frozen is set
    Logging to C:\MCEdit\mcedit2-win64-2.0.0-beta11\MCEdit 2 Files\mcedit2.log
    Setting up console handler
    Traceback (most recent call last):
      File "mcedit2\main.py", line 226, in <module>
      File "mcedit2\main.py", line 222, in main
      File "mcedit2\util\profiler.py", line 73, in _wrapper
      File "mcedit2\main.py", line 172, in startup
      File "mcedit2\sentry.py", line 15, in get_sentry_client
      File "site-packages\raven\base.py", line 177, in __init__
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 4: ordinal not in range(128)
    Failed to execute script main
    LOADER: OK.
    LOADER: Cleaning up Python interpreter.
    LOADER: Back to parent (RC: -1)
    LOADER: Doing cleanup
    LOADER: Freeing archive status for C:\MCEdit\mcedit2-win64-2.0.0-beta11\mcedit2.exe

There must be an error in source code or unhandled exception. Nothing else could produce traceback message. 32bit version prints out exactly the same output.

Target system: Windows 10 64bit
AMD Quad-Core A6-6310, 2.4 GHz
AMD Radeon R5 M240, 2 GB dedicated VRAM
4 GB DDR3 L RAM

**Comment by filipef101** [comment]
i'm getting the same, main.py line 266

**Comment by filipef101** [comment]
Ps, had to use mcedit-unified, this tool doesn't work for me both windows and osx

**Comment by wolforcept** [comment]
Is there a fix for this yet? I'm having the same problem

**Comment by filipef101** [comment]
use mcedit v1

**Comment by filipef101** [comment]
I mean, mcedit-unified, best thing
