### ISSUE TITLE
Unhandled exception when trying to run MCedit2

### ISSUE THREAD

**Issue by kalizy** [mcedit/mcedit2#386]
MCEdit version: 2.0.0-beta11
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-10-10.0.16299
Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'

this has been the error i've been getting everytime i try to run the application

**Comment by codewarrior0** [comment]
Should be fixed in beta12

**Comment by bit2shift** [comment]
Not fixed. Why is it trying to access a key in portuguese?

**Comment by bit2shift** [comment]
https://github.com/mcedit/mcedit2/blob/master/src/mcedit2/editorapp.py#L56
String translation is being applied before formatting when it should be the other way around.
```diff
-        self.setWindowTitle(self.tr("MCEdit %(version)s") % {"version": v})
+        self.setWindowTitle(self.tr("MCEdit %(version)s" % {"version": v}))
```
