### ISSUE TITLE
Error when trying to load the world

### ISSUE THREAD

**Issue by Kondzik3107** [mcedit/mcedit2#389]
Description of Issue: The problem occurred after the skyscraper was loaded into my world. Before that, MCEdit was working properly.

MCEdit Version: 2.0.0beta-12

Minecraft Version the world was last opened in: 1.12.2

Operating System: Windows 10 Home, 64-bit

A screenshot or full text of the error from the console: An error occurred while opening
C:\Users\KAMaN\AppData\Roaming.minecraft\saves\world
a float is required
Traceback (most recent call last):
File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
File "mcedit2\editorsession.py", line 190, in init (self is a EditorSession)
TypeError: a float is required

**Comment by codewarrior0** [comment]
Which language are you using?

**Comment by Kondzik3107** [comment]
Polish.
