### ISSUE TITLE
Build error on Ubuntu

### ISSUE THREAD

**Issue by kylerchin** [mcedit/mcedit2#397]
Hello! I got an install error while trying to build MCEdit2 on my Ubuntu Machine.
I have all the dependencies installed, and I'm running this as root.
I think something is wrong. Maybe better documentation could help.

```running develop
running egg_info
writing requirements to src/mcedit2.egg-info/requires.txt
writing src/mcedit2.egg-info/PKG-INFO
writing top-level names to src/mcedit2.egg-info/top_level.txt
writing dependency_links to src/mcedit2.egg-info/dependency_links.txt
writing entry points to src/mcedit2.egg-info/entry_points.txt
reading manifest file 'src/mcedit2.egg-info/SOURCES.txt'
writing manifest file 'src/mcedit2.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/blockmodels.so -> src/mcedit2/rendering
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/modelmesh.so -> src/mcedit2/rendering
Creating /usr/local/lib/python2.7/dist-packages/mcedit2.egg-link (link to src)
mcedit2 2.0.0a1.dev0 is already the active version in easy-install.pth
Installing mcedit2 script to /usr/local/bin

Installed /home/user/mcedit2/src
Processing dependencies for mcedit2==2.0.0a1.dev0
Searching for numpy==1.12.1
Best match: numpy 1.12.1
Adding numpy 1.12.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for mcedit2==2.0.0a1.dev0
Compiling src/mceditlib/relight/with_cython.pyx because it changed.
[1/1] Cythonizing src/mceditlib/relight/with_cython.pyx

Error compiling Cython file:
------------------------------------------------------------
...
DEF OUTPUT_STATS = False
IF OUTPUT_STATS:
    import time

cdef struct RelightSection:
    unsigned short[:,:,:] Blocks
                         ^
------------------------------------------------------------

src/mceditlib/relight/with_cython.pyx:30:26: C struct/union member cannot be a memory view

Error compiling Cython file:
------------------------------------------------------------
...
IF OUTPUT_STATS:
    import time

cdef struct RelightSection:
    unsigned short[:,:,:] Blocks
    unsigned char[:,:,:] BlockLight
                        ^
------------------------------------------------------------

src/mceditlib/relight/with_cython.pyx:31:25: C struct/union member cannot be a memory view

Error compiling Cython file:
------------------------------------------------------------
...
    import time

cdef struct RelightSection:
    unsigned short[:,:,:] Blocks
    unsigned char[:,:,:] BlockLight
    unsigned char[:,:,:] SkyLight
                        ^
------------------------------------------------------------

src/mceditlib/relight/with_cython.pyx:32:25: C struct/union member cannot be a memory view

Error compiling Cython file:
------------------------------------------------------------
...

cdef struct RelightChunk:
    # This guy is a big endian array, but Cython only wants to operate on little-endians.
    # We byteswap the entire thing on read, and if we're dirty, byteswap it all out again
    # on write.
    unsigned int[:,:] HeightMap
                     ^
------------------------------------------------------------

src/mceditlib/relight/with_cython.pyx:44:22: C struct/union member cannot be a memory view
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import setup_mceditlib
  File "/home/user/mcedit2/setup_mceditlib.py", line 28, in <module>
    compile_time_env={'IS_PY2': sys.version_info[0] < 3},
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/mceditlib/relight/with_cython.pyx```

Thanks!
Kyler

**Comment by kylerchin** [comment]
```
C struct/union member cannot be a memory view
```

**Comment by coledot** [comment]
@kylerchin fyi, you can get around this error by downgrading cython to 0.27.3. I used this command to install it:

pip install https://pypi.python.org/packages/ee/2a/c4d2cdd19c84c32d978d18e9355d1ba9982a383de87d0fcb5928553d37f4/Cython-0.27.3.tar.gz#md5=6149238287d662bd5d5e572482252493

**Comment by slawekwaga** [comment]
Confirmed on Manjaro 17.

**Comment by henrydatei** [comment]
works for me too (Ubuntu 16.04)

**Comment by ProfileFZY** [comment]
Thanks a lot!
