### ISSUE TITLE
When opening a Snapshot 18w11a map

### ISSUE THREAD

**Issue by saigonosenpai** [mcedit/mcedit2#398]
MCEdit version: 2.0.0-beta12
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.16299
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 391.01 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 960/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 486, in mouseMoveEvent (self is a CutawayWorldView)
  File "mcedit2\worldview\viewaction.py", line 221, in mouseMoveEvent (self is a TrackingMouseAction)
  File "mcedit2\editorsession.py", line 1365, in viewMouseMove (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1334, in updateStatusFromEvent (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1340, in updateStatus (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 1055, in getBlockID (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x000001615829BBC8>

**Comment by IotaSpencer** [comment]
This is due to 1.13's use of only block names, instead of block ids
Visible from here,

**`File "mceditlib\worldeditor.py", line 1055, in getBlockID (self is a WorldEditorDimension)`**

**Comment by FinnIsLame** [comment]
> This is due to 1.13's use of only block names, instead of block ids
> Visible from here,
> 
> **`File "mceditlib\worldeditor.py", line 1055, in getBlockID (self is a WorldEditorDimension)`**

What are you suppost to do with this??

**Comment by ztrglider** [comment]
Still having this issues in MCEdit 2.0.0-beta 14 and Minecraft 1.13.2.

In the preview menu, it only displays the chunks of the world I haven't modified and I get the error above when I try to edit the world.

Any fixes for it?
