### ISSUE TITLE
Getting error in win64 version saying I'm win32 but I'm not

### ISSUE THREAD

**Issue by ImRodry** [mcedit/mcedit2#403]
So I tried to install MCEdit and it gave me an error saying my system is win32 and I downloaded the win64 version (I guess that's what it said I don't really understand coding) but I've checked my system and it is win64 for sure! I really don't know why this is happening please let me know and help me fix this.

Also here's the error:
MCEdit version: 2.0.0-beta12
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.16299
Processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'

**Comment by solo-consummation** [comment]
I doubt MCEdit is polling your system incorrectly. Could you go into [System Information] (just type that without the brackets into Start) and look for "System Type"? That will settle things.

**Comment by ImRodry** [comment]
I just confirmed and my pc is indeed 64bit

solo-consummation <notifications@github.com> escreveu no dia sexta,
20/07/2018 à(s) 02:33:

**Comment by solo-consummation** [comment]
Does it say "x64-based PC"?

**Comment by ImRodry** [comment]
Yes I can give you a screenshot if you want.

**Comment by ImRodry** [comment]
No, what is that?

solo-consummation <notifications@github.com> escreveu no dia sábado,
21/07/2018 à(s) 13:58:
