### ISSUE TITLE
Can't Edit Dimension that doesn't have number ID.

### ISSUE THREAD

**Issue by syrun97** [mcedit/mcedit2#405]
Yes it happen on modded MC.
[mcedit2.log](https://github.com/mcedit/mcedit2/files/1986922/mcedit2.log)

MCEdit version: 2.0.0-beta12
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.16299
Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 391.35 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 550 Ti/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1600, in dimensionDidChange (self is a EditorTab)
  File "mcedit2\worldview\worldview.py", line 233, in setDimension (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
  File "mcedit2\worldview\minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\rendering\worldscene.py", line 235, in __init__ (self is a WorldScene)(named None)
  File "mcedit2\rendering\players.py", line 141, in __init__ (self is a PlayersNode)(named None)
  File "mceditlib\worldeditor.py", line 861, in dimNo (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 713, in dimNumberFromName (self is a WorldEditor)
ValueError: ('Could not parse a dimension number from %s', u'The_Beneath')

**Comment by syrun97** [comment]
I made Testpack w/ only forge version 14.23.3.2655 and abyssancraft version 1.9.4.9 (for non-number ID dim) and this error occurred.

[3508] PyInstaller Bootloader 3.x
[3508] LOADER: executable is C:\Users\bykim\Desktop\yongho\mcedit2.exe
[3508] LOADER: homepath is C:\Users\bykim\Desktop\yongho
[3508] LOADER: _MEIPASS2 is NULL
[3508] LOADER: archivename is C:\Users\bykim\Desktop\yongho\mcedit2.exe
[3508] LOADER: Extracting binaries
[3508] LOADER: Executing self as child
[3508] LOADER: set _MEIPASS2 to C:\Users\bykim\AppData\Local\Temp\_MEI35082
[3508] LOADER: Setting up to run child
[3508] LOADER: Creating child process
[3508] LOADER: Waiting for child process to finish...
[7928] PyInstaller Bootloader 3.x
[7928] LOADER: executable is C:\Users\bykim\Desktop\yongho\mcedit2.exe
[7928] LOADER: homepath is C:\Users\bykim\Desktop\yongho
[7928] LOADER: _MEIPASS2 is C:\Users\bykim\AppData\Local\Temp\_MEI35082
[7928] LOADER: archivename is C:\Users\bykim\Desktop\yongho\mcedit2.exe
[7928] LOADER: SetDllDirectory(C:\Users\bykim\AppData\Local\Temp\_MEI35082)
[7928] LOADER: Already in the child - running user's code.
[7928] LOADER: manifestpath: C:\Users\bykim\AppData\Local\Temp\_MEI35082\mcedit2.exe.manifest
[7928] LOADER: Activation context created
[7928] LOADER: Activation context activated
[7928] LOADER: Python library: C:\Users\bykim\AppData\Local\Temp\_MEI35082\python27.dll
[7928] LOADER: Loaded functions from Python library.
[7928] LOADER: Manipulating environment (sys.path, sys.prefix)
[7928] LOADER: sys.prefix is C:\Users\bykim\AppData\Local\Temp\_MEI35~1
[7928] LOADER: Setting runtime options
[7928] LOADER: Bootloader option: pyi-windows-manifest-filename mcedit2.exe.manifest
[7928] LOADER: Initializing python
[7928] LOADER: Overriding Python's sys.path
[7928] LOADER: Post-init sys.path is C:\Users\bykim\AppData\Local\Temp\_MEI35082
[7928] LOADER: Setting sys.argv
[7928] LOADER: setting sys._MEIPASS
[7928] LOADER: importing modules from CArchive
[7928] LOADER: extracted struct
[7928] LOADER: callfunction returned...
[7928] LOADER: extracted pyimod01_os_path
[7928] LOADER: callfunction returned...
[7928] LOADER: extracted pyimod02_archive
[7928] LOADER: callfunction returned...
[7928] LOADER: extracted pyimod03_importers
[7928] LOADER: callfunction returned...
[7928] LOADER: Installing PYZ archive with Python modules.
[7928] LOADER: PYZ archive: out00-PYZ.pyz
[7928] LOADER: Running pyiboot01_bootstrap.py
[7928] LOADER: Running pyi_rth_win32comgenpy.py
[7928] LOADER: Running pyi_rth_pkgres.py
[7928] LOADER: Running pyi_rth_multiprocessing.py
[7928] LOADER: Running pyi_rth_traitlets.py
[7928] LOADER: Running pyi_rth_qt4plugins.py
[7928] LOADER: Running main.py
Logging level set
sys.frozen is set
Logging to C:\Users\bykim\Desktop\yongho\MCEdit 2 Files\mcedit2.log
Setting up console handler
[WARNING][editorapp.py:95]:UserFilesDirectory: C:\Users\bykim\Desktop\yongho\MCEdit 2 Files
[WARNING][configure_blocks.py:121]:Failed to read definitions file defined_blocks.json
[WARNING][__init__.py:227]:Plugins dir C:\Users\bykim\Desktop\yongho\MCEdit 2 Files\plugins not found
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
[ERROR][player_server.py:85]:Error reading JSON from session server.
Traceback (most recent call last):
  File "mcedit2\util\player_server.py", line 83, in _queryFinished (self is a PlayerDataCache)
  File "json\__init__.py", line 339, in loads
  File "json\decoder.py", line 364, in decode (self is a JSONDecoder)
  File "json\decoder.py", line 382, in raw_decode (self is a JSONDecoder)
ValueError: No JSON object could be decoded
[ERROR][player_server.py:85]:Error reading JSON from session server.
Traceback (most recent call last):
  File "mcedit2\util\player_server.py", line 83, in _queryFinished (self is a PlayerDataCache)
  File "json\__init__.py", line 339, in loads
  File "json\decoder.py", line 364, in decode (self is a JSONDecoder)
  File "json\decoder.py", line 382, in raw_decode (self is a JSONDecoder)
ValueError: No JSON object could be decoded
Could not parse stylesheet of widget 0x238bb8a3f70
Could not parse stylesheet of widget 0x238bb8a59e0
Could not parse stylesheet of widget 0x238bb8a6850
Could not parse stylesheet of widget 0x238bbe9cba0
Could not parse stylesheet of widget 0x238bbe9e3a0
Could not parse stylesheet of widget 0x238bbe9f060
Could not parse stylesheet of widget 0x238bbe9f9f0
Could not parse stylesheet of widget 0x238bbea0aa0
Could not parse stylesheet of widget 0x238bbea2510
Could not parse stylesheet of widget 0x238bbea2810
Could not parse stylesheet of widget 0x238bbea3350
Exception AttributeError: "'RevisionHistory' object has no attribute 'nodes'" in <object repr() failed> ignored
QMainWindow::addDockWidget: invalid 'area' argument
[ERROR][main.py:203]:Unhandled Exception:
        ('Could not parse a dimension number from %s', u'Omothol')
Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1600, in dimensionDidChange (self is a EditorTab)
  File "mcedit2\worldview\worldview.py", line 233, in setDimension (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
  File "mcedit2\worldview\minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\rendering\worldscene.py", line 235, in __init__ (self is a WorldScene)
  File "mcedit2\rendering\players.py", line 141, in __init__ (self is a PlayersNode)
  File "mceditlib\worldeditor.py", line 861, in dimNo (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 713, in dimNumberFromName (self is a WorldEditor)
ValueError: ('Could not parse a dimension number from %s', u'Omothol')
