### ISSUE TITLE
Completely broken...

### ISSUE THREAD

**Issue by xxmadbrinexx** [mcedit/mcedit2#407]
I'm trying to open an 18w20c snapshot save and as soon as I do, the world looks empty and it gives me an error when I move the mouse.

Error:
```
MCEdit version: 2.0.0-beta12
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 388.13 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 1050 Ti/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 480, in mouseMoveEvent (self is a CameraWorldView)
  File "mcedit2\worldview\worldview.py", line 527, in augmentMouseEvent (self is a CameraWorldView)
  File "mcedit2\worldview\camera.py", line 330, in augmentEvent (self is a CameraWorldView)
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\worldview\worldview.py", line 548, in augmentEvent (self is a CameraWorldView)
  File "mcedit2\worldview\worldview.py", line 615, in rayCastInView (self is a CameraWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x000001D61B1EC1C8>
```
By the looks of it I'm guessing since I have blocks from the snapshot that it's not working... "Key blocks not found." But in other versions, if it found a block that it didn't know how to display, it would just show a question mark. I can load 1.12.2 worlds *with mods* and they still work. Help please?

**Comment by codewarrior0** [comment]
1.13 is not yet supported.

**Comment by xxmadbrinexx** [comment]
Oh... Can you at least tell me why it said "Missing key blocks?"

**Comment by codewarrior0** [comment]
Because 1.13 is not yet supported.
