### ISSUE TITLE
Can't open mcedit. Can someone help?

### ISSUE THREAD

**Issue by DiamondHunter85** [mcedit/mcedit2#421]
Can't even open it. Steps to reproduce: open the file.

Error:

MCEdit version: 2.0.0-beta12
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'

**Comment by Kaiser145** [comment]
I have the same problem!

(It says is have win32, but i have 64bit windows)

The Error:

MCEdit version: 2.0.0-beta12
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel


------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'

**Comment by kikasmelo** [comment]
I have the same problem!
[INFO][main.py:177]:MCEdit2 version 2.0.0-beta12 starting...
[INFO][acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[INFO][settings.py:112]:Loading app settings from C:\Users\gugaxz\Downloads\mcedit2-win64-2.0.0-beta12\MCEdit 2 Files\mcedit2.ini
[INFO][loadablechunks.py:17]:Making checkerboard texture...
[WARNING][editorapp.py:95]:UserFilesDirectory: C:\Users\gugaxz\Downloads\mcedit2-win64-2.0.0-beta12\MCEdit 2 Files
[INFO][editorapp.py:120]:Loaded translator. Selected language: pt_PT
[INFO][editorapp.py:150]:Loaded stylesheet.
[ERROR][main.py:203]:Unhandled Exception: 
	u'vers\xe3o'
Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>  
  File "mcedit2\main.py", line 222, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 193, in startup  
  File "mcedit2\editorapp.py", line 154, in __init__ (self is a MCEditApp)
  File "mcedit2\editorapp.py", line 56, in __init__ (self is a MCEditMainWindow)
KeyError: u'vers\xe3o'
[ERROR][base.py:672]:Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
[ERROR][base.py:700]:[u"KeyError: u'vers\\xe3o'", u'  File "mcedit2\\main.py", line 226, in <module>', u'  File "mcedit2\\main.py", line 222, in main', u'  File "mcedit2\\util\\profiler.py", line 73, in _wrapper', u'  File "mcedit2\\main.py", line 193, in startup', u'  File "mcedit2\\editorapp.py", line 154, in __init__', u'  File "mcedit2\\editorapp.py", line 56, in __init__']
