### ISSUE TITLE
mcedit 2 cant open world error code

### ISSUE THREAD

**Issue by cemmao** [mcedit/mcedit2#422]
Click the "guidelines for contributing" link above and read it. If you do not supply the
needed information, your issue will be closed without comment.
so i have updated java, nvidia. i have uninstalled and reinstalled minecraft and mcedit. im pulling my hair out at this point as i have no idea what else to try as all internet searches come up with stuff i either dont understanmd or just the wrong issue. so here is a copy and pasta of the error. if anyone could help it would be amazing.
An error occurred while opening C:\Users\cemma\AppData\Roaming\.minecraft\saves\pokemon
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

this code comes up once ive click edit x

**Comment by merklen** [comment]
I have the same problem

**Comment by Juno808** [comment]
Same problem.

OS X version of 2.0.0-beta14

I get the following error message.

'SchematicFileAdapter' object has no attribute 'requireRevisions'

Traceback (most recent call last):
  File "mcedit2/editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2/editorsession.py", line 211, in __init__ (self is a EditorSession)
  File "mceditlib/worldeditor.py", line 284, in requireRevisions (self is a WorldEditor)
AttributeError: 'SchematicFileAdapter' object has no attribute 'requireRevisions'

**Comment by L0calH0rst** [comment]
exactly the same error on win 10 64bit trying to open a 1.13.2 world

**Comment by danielassada** [comment]
same problem

An error occurred while opening C:\Users\danie\AppData\Roaming\.minecraft\saves\Red biD
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

anyone has a solution?
