### ISSUE TITLE
MCEdit 2.0.0 beta14 not working

### ISSUE THREAD

**Issue by IBoopUrNoes** [mcedit/mcedit2#428]
When I run mcedit and edit a world, it gives me this error message-
`MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 391.35 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 1080/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x32F68B20>
`
I am using a 64bit computer, ask me for any more info needed. Ty in advance

**Comment by RoboticRice** [comment]
What version of Minecraft was the world last opened in?

The Aquatic Updates of Minecraft (Java 1.13 and 1.13.1) are not supported by any version of MCEdit 1, MCEdit 2, or MCEdit Unified - this is b/c Minecraft completely changed the way it identifies blocks and it is not compatible with current versions of MCEdit software.

**Comment by TomatoSenpai** [comment]
> 
> 
> What version of Minecraft was the world last opened in?
> 
> The Aquatic Updates of Minecraft (Java 1.13 and 1.13.1) are not supported by any version of MCEdit 1, MCEdit 2, or MCEdit Unified - this is b/c Minecraft completely changed the way it identifies blocks and it is not compatible with current versions of MCEdit software.

When do you think we will get an 1.13 update?

**Comment by RoboticRice** [comment]
According to the Discord group, they are planning on dropping support for MCEdit in future versions, in order to support their new project that will be able to support ANY version of minecraft. I believe it's called Amulet.

From what I understand, Amulet will take the save file and convert it into a proprietary "Amulet Code" so they only have to program edits for the Amulet Code, instead of make the same task for each version of minecraft code (Java Pre-Aquatic, Java Aquatic, Bedrock Pre-Aquatic, Bedrock Aquatic, etc.)

**Comment by LolekLiam** [comment]
i get an error too but i'm using minecraft 1.15.2

**Comment by RoboticRice** [comment]
> i get an error too but i'm using minecraft 1.15.2
Dude, you just replied to a thread from 2018. The version of MCEdit we were talking about didnt support 1.13, why would it support 1.15?

I'm not up-to-date with the current version of MCEdit, haven't used it in about a year now, but you need to go on their reddit or discord and speak and check if they support your version or not.

**Comment by TomatoSenpai** [comment]
> 
> 
> i get an error too but i'm using minecraft 1.15.2

Hello! I also got a notification from this, please do not revive dead threads!

This is "deprecated" software, since they don't support it anymore, have a nice day.
