### ISSUE TITLE
Problem with MC Edit 2.0.0 beta 14

### ISSUE THREAD

**Issue by Clafter** [mcedit/mcedit2#429]
Hi i wanted to join a world in the version 1.13.1 an then came that massage:

MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: AMD64 Family 21 Model 19 Stepping 1, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.13399 Compatibility Profile Context 15.201.1151.1008 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon HD 8570D'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 502, in wheelEvent (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 527, in augmentMouseEvent (self is a MinimapWorldView)
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\worldview\worldview.py", line 548, in augmentEvent (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 615, in rayCastInView (self is a MinimapWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x0E5EFCB0>

Do you can help me?
Thanks!
Bye

**Comment by RoboticRice** [comment]
The Aquatic Updates of Minecraft (Java 1.13 and 1.13.1) are not supported by any version of MCEdit 1, MCEdit 2, or MCEdit Unified - this is b/c Minecraft completely changed the way it identifies blocks and it is not compatible with current versions of MCEdit software.

**Comment by TylerCode** [comment]
@RoboticRice So it's not just an issue of the new blocks missing? Looking at it now.
