### ISSUE TITLE
wont load 1.13.1

### ISSUE THREAD

**Issue by kmddd59** [mcedit/mcedit2#430]
[17780] PyInstaller Bootloader 3.x
[17780] LOADER: executable is I:\Downloads\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[17780] LOADER: homepath is I:\Downloads\mcedit2-win64-2.0.0-beta14
[17780] LOADER: _MEIPASS2 is NULL
[17780] LOADER: archivename is I:\Downloads\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[17780] LOADER: Extracting binaries
[17780] LOADER: Executing self as child
[17780] LOADER: set _MEIPASS2 to C:\Users\varax\AppData\Local\Temp\_MEI177802
[17780] LOADER: Setting up to run child
[17780] LOADER: Creating child process
[17780] LOADER: Waiting for child process to finish...
[13776] PyInstaller Bootloader 3.x
[13776] LOADER: executable is I:\Downloads\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[13776] LOADER: homepath is I:\Downloads\mcedit2-win64-2.0.0-beta14
[13776] LOADER: _MEIPASS2 is C:\Users\varax\AppData\Local\Temp\_MEI177802
[13776] LOADER: archivename is I:\Downloads\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[13776] LOADER: SetDllDirectory(C:\Users\varax\AppData\Local\Temp\_MEI177802)
[13776] LOADER: Already in the child - running user's code.
[13776] LOADER: manifestpath: C:\Users\varax\AppData\Local\Temp\_MEI177802\mcedit2.exe.manifest
[13776] LOADER: Activation context created
[13776] LOADER: Activation context activated
[13776] LOADER: Python library: C:\Users\varax\AppData\Local\Temp\_MEI177802\python27.dll
[13776] LOADER: Loaded functions from Python library.
[13776] LOADER: Manipulating environment (sys.path, sys.prefix)
[13776] LOADER: sys.prefix is C:\Users\varax\AppData\Local\Temp\_MEI17~1
[13776] LOADER: Setting runtime options
[13776] LOADER: Bootloader option: pyi-windows-manifest-filename mcedit2.exe.manifest
[13776] LOADER: Initializing python
[13776] LOADER: Overriding Python's sys.path
[13776] LOADER: Post-init sys.path is C:\Users\varax\AppData\Local\Temp\_MEI177802
[13776] LOADER: Setting sys.argv
[13776] LOADER: setting sys._MEIPASS
[13776] LOADER: importing modules from CArchive
[13776] LOADER: extracted struct
[13776] LOADER: callfunction returned...
[13776] LOADER: extracted pyimod01_os_path
[13776] LOADER: callfunction returned...
[13776] LOADER: extracted pyimod02_archive
[13776] LOADER: callfunction returned...
[13776] LOADER: extracted pyimod03_importers
[13776] LOADER: callfunction returned...
[13776] LOADER: Installing PYZ archive with Python modules.
[13776] LOADER: PYZ archive: out00-PYZ.pyz
[13776] LOADER: Running pyiboot01_bootstrap.py
[13776] LOADER: Running pyi_rth_win32comgenpy.py
[13776] LOADER: Running pyi_rth_pkgres.py
[13776] LOADER: Running pyi_rth_multiprocessing.py
[13776] LOADER: Running pyi_rth_traitlets.py
[13776] LOADER: Running pyi_rth_qt4plugins.py
[13776] LOADER: Running main.py
Logging level set
sys.frozen is set
Logging to I:\Downloads\mcedit2-win64-2.0.0-beta14\MCEdit 2 Files\mcedit2.log
Setting up console handler
[WARNING][editorapp.py:95]:UserFilesDirectory: I:\Downloads\mcedit2-win64-2.0.0-beta14\MCEdit 2 Files
[WARNING][configure_blocks.py:121]:Failed to read definitions file defined_blocks.json

MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 387.95 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 1070/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x000001CBCD0CD0C8>
![image](https://user-images.githubusercontent.com/5413229/45244886-c0f02600-b2c7-11e8-93f5-423e37e3d7f8.png)

**Comment by RoboticRice** [comment]
The Aquatic Updates of Minecraft (Java 1.13 and 1.13.1) are not supported by any version of MCEdit 1, MCEdit 2, or MCEdit Unified - this is b/c Minecraft completely changed the way it identifies blocks and it is not compatible with current versions of MCEdit software.

**Comment by sbliven** [comment]
Duplicate of #420
