### ISSUE TITLE
McEdit error no matter what version

### ISSUE THREAD

**Issue by Chillthuggin1** [mcedit/mcedit2#438]
Okay so every time I launch McEdit it just show this message:
MCEdit version: 2.0.0-beta1
Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.15063
Processor: AMD64 Family 21 Model 101 Stepping 1, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.13506 Compatibility Profile Context 23.20.15017.3010 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon R5 Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\worldlist.py", line 476, in loadTimerFired (self is a WorldListWidget)
  File "mcedit2\rendering\chunkloader.py", line 205, in next (self is a ChunkLoader)
  File "mcedit2\rendering\chunkloader.py", line 244, in _loadChunks (self is a ChunkLoader)
  File "mcedit2\rendering\chunkloader.py", line 275, in _loadChunk (self is a ChunkLoader)
  File "mceditlib\worldeditor.py", line 807, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 501, in getChunk (self is a WorldEditor)
  File "mceditlib\worldeditor.py", line 76, in __len__  
  File "mceditlib\anvil\adapter.py", line 315, in Entities (self is a AnvilChunkData)
  File "src\mceditlib\nbt.pyx", line 445, in mceditlib.nbt._TAG_Compound.__getitem__ (src/mceditlib/nbt.c:9677)  
KeyError: 'Key Entities not found.'

No matter what version I download it still has the same error I just launch McEdit then a few seconds later it just pops up like 15 of the same errors!

**Comment by PassTheMayo** [comment]
Yeah, I have the same problem too.

**Comment by dblack923** [comment]
Same here. I've tried to open 1.11

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 486, in mouseMoveEvent (self is a CameraWorldView)
  File "mcedit2\worldview\viewaction.py", line 221, in mouseMoveEvent (self is a TrackingMouseAction)
  File "mcedit2\editorsession.py", line 1365, in viewMouseMove (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1334, in updateStatusFromEvent (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1340, in updateStatus (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 1055, in getBlockID (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__ (self is a lru_cache_object)
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x00000131FAFA77C8>
