### ISSUE TITLE
ImportError: No module named QtOpenGL

### ISSUE THREAD

**Issue by purpleposeidon** [mcedit/mcedit2#439]
```
$ . ./ENV/bin/activate
(ENV) $ pip install -r requirements.txt
Requirement already satisfied: cython==0.26 in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 1)) (0.26)
Requirement already satisfied: numpy in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 2)) (1.15.3)
Requirement already satisfied: arrow in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 3)) (0.12.1)
Requirement already satisfied: pyzmq==15.0.0 in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (15.0.0)
Requirement already satisfied: pyside>=1.2.0 in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.2.4)
Requirement already satisfied: pyopengl in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: ipython in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (5.8.0)
Requirement already satisfied: qtconsole in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (4.4.2)
Requirement already satisfied: pygments in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (2.2.0)
Requirement already satisfied: pastebin in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.1.2)
Requirement already satisfied: raven in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 9)) (6.9.0)
Requirement already satisfied: backports.functools-lru-cache>=1.2.1; python_version == "2.7" in ./ENV/lib/python2.7/site-packages (from arrow->-r requirements-mceditlib.txt (line 3)) (1.5)
Requirement already satisfied: python-dateutil in ./ENV/lib/python2.7/site-packages (from arrow->-r requirements-mceditlib.txt (line 3)) (2.7.5)
Requirement already satisfied: simplegeneric>0.8 in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (0.8.1)
Requirement already satisfied: pickleshare in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (0.7.5)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (2.3.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (4.6.0)
Requirement already satisfied: traitlets>=4.2 in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (4.3.2)
Requirement already satisfied: decorator in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (4.3.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (1.0.15)
Requirement already satisfied: setuptools>=18.5 in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5)) (40.5.0)
Requirement already satisfied: ipykernel>=4.1 in ./ENV/lib/python2.7/site-packages (from qtconsole->-r requirements.txt (line 6)) (4.10.0)
Requirement already satisfied: jupyter-client>=4.1 in ./ENV/lib/python2.7/site-packages (from qtconsole->-r requirements.txt (line 6)) (5.2.3)
Requirement already satisfied: jupyter-core in ./ENV/lib/python2.7/site-packages (from qtconsole->-r requirements.txt (line 6)) (4.4.0)
Requirement already satisfied: ipython-genutils in ./ENV/lib/python2.7/site-packages (from qtconsole->-r requirements.txt (line 6)) (0.2.0)
Requirement already satisfied: contextlib2; python_version < "3.2" in ./ENV/lib/python2.7/site-packages (from raven->-r requirements.txt (line 9)) (0.5.5)
Requirement already satisfied: six>=1.5 in ./ENV/lib/python2.7/site-packages (from python-dateutil->arrow->-r requirements-mceditlib.txt (line 3)) (1.11.0)
Requirement already satisfied: scandir; python_version < "3.5" in ./ENV/lib/python2.7/site-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython->-r requirements.txt (line 5)) (1.9.0)
Requirement already satisfied: ptyprocess>=0.5 in ./ENV/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->ipython->-r requirements.txt (line 5)) (0.6.0)
Requirement already satisfied: enum34; python_version == "2.7" in ./ENV/lib/python2.7/site-packages (from traitlets>=4.2->ipython->-r requirements.txt (line 5)) (1.1.6)
Requirement already satisfied: wcwidth in ./ENV/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->-r requirements.txt (line 5)) (0.1.7)
Requirement already satisfied: tornado>=4.0 in ./ENV/lib/python2.7/site-packages (from ipykernel>=4.1->qtconsole->-r requirements.txt (line 6)) (5.1.1)
Requirement already satisfied: futures in ./ENV/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6)) (3.2.0)
Requirement already satisfied: singledispatch in ./ENV/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6)) (3.4.0.3)
Requirement already satisfied: backports-abc>=0.4 in ./ENV/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6)) (0.5)
(ENV) $ python setup.py develop
running develop
running egg_info
writing requirements to src/mcedit2.egg-info/requires.txt
writing src/mcedit2.egg-info/PKG-INFO
writing top-level names to src/mcedit2.egg-info/top_level.txt
writing dependency_links to src/mcedit2.egg-info/dependency_links.txt
writing entry points to src/mcedit2.egg-info/entry_points.txt
reading manifest file 'src/mcedit2.egg-info/SOURCES.txt'
writing manifest file 'src/mcedit2.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/blockmodels.so -> src/mcedit2/rendering
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/modelmesh.so -> src/mcedit2/rendering
Creating /home/poseidon/mc/mcedit2/mcedit2/ENV/lib/python2.7/site-packages/mcedit2.egg-link (link to src)
mcedit2 2.0.0a1.dev0 is already the active version in easy-install.pth
Installing mcedit2 script to /home/poseidon/mc/mcedit2/mcedit2/ENV/bin

Installed /home/poseidon/mc/mcedit2/mcedit2/src
Processing dependencies for mcedit2==2.0.0a1.dev0
Searching for numpy==1.15.3
Best match: numpy 1.15.3
Adding numpy 1.15.3 to easy-install.pth file

Using /home/poseidon/mc/mcedit2/mcedit2/ENV/lib/python2.7/site-packages
Finished processing dependencies for mcedit2==2.0.0a1.dev0
running develop
running egg_info
writing requirements to src/mceditlib.egg-info/requires.txt
writing src/mceditlib.egg-info/PKG-INFO
writing top-level names to src/mceditlib.egg-info/top_level.txt
writing dependency_links to src/mceditlib.egg-info/dependency_links.txt
reading manifest file 'src/mceditlib.egg-info/SOURCES.txt'
writing manifest file 'src/mceditlib.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/mceditlib/nbt.so -> src/mceditlib
copying build/lib.linux-x86_64-2.7/mceditlib/relight/with_cython.so -> src/mceditlib/relight
Creating /home/poseidon/mc/mcedit2/mcedit2/ENV/lib/python2.7/site-packages/mceditlib.egg-link (link to src)
mceditlib 2.0.0a1.dev0 is already the active version in easy-install.pth

Installed /home/poseidon/mc/mcedit2/mcedit2/src
Processing dependencies for mceditlib==2.0.0a1.dev0
Searching for numpy==1.15.3
Best match: numpy 1.15.3
Adding numpy 1.15.3 to easy-install.pth file

Using /home/poseidon/mc/mcedit2/mcedit2/ENV/lib/python2.7/site-packages
Finished processing dependencies for mceditlib==2.0.0a1.dev0
(ENV) $ mcedit2
Logging level set
Logging to /home/poseidon/mc/mcedit2/mcedit2/MCEdit 2 Files/mcedit2.log
Setting up console handler
[ERROR][main.py:203]:Unhandled Exception: 
        No module named QtOpenGL
Traceback (most recent call last):
  File "/home/poseidon/mc/mcedit2/mcedit2/ENV/bin/mcedit2", line 11, in <module>  
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/main.py", line 222, in main  
    app = startup()
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/main.py", line 188, in startup  
    from mcedit2.editorapp import MCEditApp
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/editorapp.py", line 14, in <module>  
    from mcedit2 import plugins
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/plugins/__init__.py", line 13, in <module>  
    from mcedit2.editortools import generate
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/editortools/generate.py", line 17, in <module>  
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/rendering/worldscene.py", line 14, in <module>  
    from mcedit2.rendering.players import PlayersNode
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/rendering/players.py", line 16, in <module>  
    from mcedit2.util.load_png import loadPNGTexture, loadPNGFile
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/util/load_png.py", line 5, in <module>  
    from PySide.QtOpenGL import QGLWidget
ImportError: No module named QtOpenGL
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/main.py", line 217, in excepthook
    from mcedit2.dialogs.error_dialog import showErrorDialog
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/dialogs/error_dialog.py", line 14, in <module>
    from mcedit2.util import qglcontext
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/util/qglcontext.py", line 6, in <module>
    from PySide import QtOpenGL, QtGui
ImportError: cannot import name QtOpenGL

Original exception was:
Traceback (most recent call last):
  File "/home/poseidon/mc/mcedit2/mcedit2/ENV/bin/mcedit2", line 11, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/main.py", line 222, in main
    app = startup()
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/util/profiler.py", line 73, in _wrapper
    return func(*a, **kw)
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/main.py", line 188, in startup
    from mcedit2.editorapp import MCEditApp
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/editorapp.py", line 14, in <module>
    from mcedit2 import plugins
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/plugins/__init__.py", line 13, in <module>
    from mcedit2.editortools import generate
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/editortools/generate.py", line 17, in <module>
    from mcedit2.rendering.worldscene import WorldScene
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/rendering/worldscene.py", line 14, in <module>
    from mcedit2.rendering.players import PlayersNode
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/rendering/players.py", line 16, in <module>
    from mcedit2.util.load_png import loadPNGTexture, loadPNGFile
  File "/home/poseidon/mc/mcedit2/mcedit2/src/mcedit2/util/load_png.py", line 5, in <module>
    from PySide.QtOpenGL import QGLWidget
ImportError: No module named QtOpenGL
(ENV) $ which python
/home/poseidon/mc/mcedit2/mcedit2/ENV/bin/python
(ENV) $ python --version
Python 2.7.15rc1
(ENV) $ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PySide
>>> PySide.__version__
'1.2.4'
>>> import PySide.QtOpenGL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named QtOpenGL
```
Ubuntu 18.04.1 LTS
Linux obelisk 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by devoncrouse** [comment]
Found a work-around; put a system copy of QtOpenGL.so in the site-packages of the virtualenv...
```
mcedit2/build/lib/python2.7/site-packages/PySide$ cp /usr/lib/python2.7/dist-packages/PySide/QtOpenGL.so .
```
