### ISSUE TITLE
McEdit Crashes when i open a world

### ISSUE THREAD

**Issue by EpicSkullYT** [mcedit/mcedit2#440]
When I open a 1.13.2 Minecraft world I get an error. Does anyone know a fix or can it not be fixed?

MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 399.07 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GT 710/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x162B7A08>

**Comment by SliceThePi** [comment]
Unfortunately, MCEdit currently won't work with 1.13. The 1.13 world format is different enough from Anvil that large sections of MCEdit are going to need to be rewritten. If you know how to run Python programs from source, the latest version of MCEdit Unified *may* work with 1.13, as it was updated recently. (No guarantees, though- I haven't tested it myself, and only gave the repository a quick glance. The update could just be a bugfix.)
https://github.com/Podshot/MCEdit-Unified
