### ISSUE TITLE
MCEdit Crashes when opening worlds affected by 1.13.2

### ISSUE THREAD

**Issue by MatthewStevenGo** [mcedit/mcedit2#446]
Log:

MCEdit version: 2.0.0-beta6
Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 388.57 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 610M/PCIe/SSE2'

Unhandled Exception

Traceback (most recent call last):
File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
File "mcedit2\worldlist.py", line 476, in loadTimerFired (self is a WorldListWidget)
File "mcedit2\rendering\chunkloader.py", line 205, in next (self is a ChunkLoader)
File "mcedit2\rendering\chunkloader.py", line 244, in _loadChunks (self is a ChunkLoader)
File "mcedit2\rendering\chunkloader.py", line 275, in _loadChunk (self is a ChunkLoader)
File "mceditlib\worldeditor.py", line 807, in getChunk (self is a WorldEditorDimension)
File "mceditlib\worldeditor.py", line 495, in getChunk (self is a WorldEditor)
File "mceditlib\cachefunc.py", line 77, in call
File "mceditlib\worldeditor.py", line 473, in _getChunkDataRaw (self is a WorldEditor)
File "mceditlib\anvil\adapter.py", line 892, in readChunk (self is a AnvilWorldAdapter)
File "src\mceditlib\nbt.pyx", line 569, in mceditlib.nbt.load (src/mceditlib/nbt.c:12098)
File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)
File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)
File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)
File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)
File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)
File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)
File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)
File "src\mceditlib\nbt.pyx", line 668, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13041)
File "src\mceditlib\nbt.pyx", line 709, in mceditlib.nbt.load_name (src/mceditlib/nbt.c:13470)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 6: invalid start byte

The OS I am using is the Windows 10 Professional.
The MCEdit version I am using is 2.0.0-beta6 and the 0.1.7.1
The Minecraft version used when opening the map in question (from 1.12.2 and below) is 1.13.2.

Here is how it started:
= I opened Minecraft using the 1.13.2 for the first time, and then opened the old worlds, and things went well until one fateful event... I tried to load these worlds (affected by 1.13.2) using the 1.12.2 and things did not go as planned = Everything went blank. Fortunately, I duplicated the world in question before doing the process. When I tried opening the world affected by the 1.13.2 version, MCEdit shows the error while trying to load the said affected world.

**Comment by MatthewStevenGo** [comment]
Apologies if I might not be able to follow the instructions well initially.

**Comment by Rambo99** [comment]
I have the same problem. #463

**Comment by Hacker719** [comment]
Same here
