### ISSUE TITLE
Just got mcedit none of my worlds work

### ISSUE THREAD

**Issue by Lit4200** [mcedit/mcedit2#453]
I open mc edit click the world i want then click edit and an error pops up. Im using McEdit2.0.0-beta14. im on windows. 
An error occurred while opening C:\Users\noahb\AppData\Roaming\.minecraft\saves\New World-
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

**Comment by qualitywaffles** [comment]
Im having the same issue. is it just an error with how the file was saved?
how do i fix this.
