### ISSUE TITLE
MCEdit cant edit 1.13/1.14 worlds!

### ISSUE THREAD

**Issue by PanequePanaca** [mcedit/mcedit2#456]
An error occurred while opening C:\Users\Ian\AppData\Roaming\.minecraft\saves\Novo mundo
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

**Comment by Lit4200** [comment]
exactly what i got

**Comment by Luysita** [comment]
Please fix it!

**Comment by J0SLAN** [comment]
They are fixing it, calm yourselves, it's a huge jump from 1.12- to 1.13+ because MC save data was majorly overhauled

**Comment by Rambo99** [comment]
I have the same problem. #463

**Comment by andyr117** [comment]
Yeah I have the same problem when trying to edit on 1.13+

**Comment by Thedude7054** [comment]
Do we have a rough timeline on completion of this feature, even a rough implementation?

**Comment by XGNXLency** [comment]
Same problem here. No fix yet. Thanks devs.

**Comment by sbliven** [comment]
Duplicate of #420

**Comment by FinnT730** [comment]
They are working on a new editor.
Please see this issue of me explaining what is gong on: https://github.com/mcedit/mcedit2/issues/518
