### ISSUE TITLE
Error while trying to open the world. MCEdit 2. Minecraft 1.13.2

### ISSUE THREAD

**Issue by Rambo99** [mcedit/mcedit2#463]
MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 417.71 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 980/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 480, in mouseMoveEvent (self is a CameraWorldView)
  File "mcedit2\worldview\worldview.py", line 527, in augmentMouseEvent (self is a CameraWorldView)
  File "mcedit2\worldview\camera.py", line 330, in augmentEvent (self is a CameraWorldView)
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\worldview\worldview.py", line 548, in augmentEvent (self is a CameraWorldView)
  File "mcedit2\worldview\worldview.py", line 615, in rayCastInView (self is a CameraWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x00000000242A7A48>

**Comment by Wsmalle** [comment]
1.13.2 is not supported.
