### ISSUE TITLE
No OpenGL_accelerate module loaded: No module named OpenGL_accelerate

### ISSUE THREAD

**Issue by SpeedrunnerG55** [mcedit/mcedit2#469]
crashes on startup

`[INFO][main.py:177]:MCEdit2 version HOMEBAKED starting...
[INFO][acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[ERROR][main.py:203]:Unhandled Exception: 
	No module named block_picker_multiple
Traceback (most recent call last):
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/ENV/bin/mcedit2", line 11, in <module>  
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/main.py", line 222, in main  
    app = startup()
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/main.py", line 188, in startup  
    from mcedit2.editorapp import MCEditApp
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/editorapp.py", line 14, in <module>  
    from mcedit2 import plugins
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/plugins/__init__.py", line 13, in <module>  
    from mcedit2.editortools import generate
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/editortools/generate.py", line 20, in <module>  
    from mcedit2.widgets.layout import Column
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/widgets/__init__.py", line 7, in <module>  
    import blockpicker
  File "/home/speed/Downloads/mcedit2/mcedit2-2.0.0-beta14/src/mcedit2/widgets/blockpicker.py", line 12, in <module>  
    from mcedit2.ui.widgets.block_picker_multiple import Ui_blockPickerMultiple
ImportError: No module named block_picker_multiple`

using version 2.0.0-beta14

on ubuntu 18.04

using python 2.7.15rc1

**Comment by RedNicStone** [comment]
Same issue here to :/

running Fedora 29

I'm curious how this would work anyway (this is .ui not .py?!):
![block_picker_mutiple](https://user-images.githubusercontent.com/36967667/57182212-e22c0500-6e9c-11e9-9280-827cd9b0bb29.png)

**Comment by RedNicStone** [comment]
The problem: not properly prebuild project

The solution: grab your pyuic* (/usr/lib64/python2.7/site-packages/PyQt4/uic/pyuic.py on my device)
and convert EVERY SINGLE .ui file by typing pyuic filename.ui > filename.py

*included in the PyQt package
