### ISSUE TITLE
Unhandled exception -- Cannot load world

### ISSUE THREAD

**Issue by greyboxxing** [mcedit/mcedit2#478]
Loading all worlds up from 1.14.1 results in the following error: 
```
MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8.1-6.3.9600
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.13474 Compatibility Profile Context 22.19.162.4 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon (TM) R9 390 Series'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x00000034089AC648>
```
I saw a lot about a lack of support for 1.13 and beyond, but all posts about that issue were from early 2018.

**Comment by kam1sh** [comment]
Hey, I have this issue too!

 I looked at the source code, but this exception is just a wrapper without the root cause =( 
https://github.com/mcedit/mcedit2/blob/4bb98da521447b6cf43d923cea9f00acf2f427e9/src/mceditlib/anvil/adapter.py#L904-L924

I also tried to find how to enable debug logging and couldn't. Even developer mode does not enable that. 

There's documentation about chunk format at the [Minecraft wiki](https://minecraft.gamepedia.com/Chunk_format), but idk is it actual or outdated.

Will dig into that next weekend.
