### ISSUE TITLE
Can't use MCEdit for any of my worlds

### ISSUE THREAD

**Issue by Newnande** [mcedit/mcedit2#500]
MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17763
Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 - Build 25.20.100.6576 (4, 5)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) UHD Graphics 620'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 590, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 282, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 96, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 96, in compile (self is a RenderNode)
  File "mcedit2\rendering\loadablechunks.py", line 33, in compile (self is a LoadableChunksRenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 103, in compile (self is a LoadableChunksRenderNode)
  File "mcedit2\util\glutils.py", line 132, in compile (self is a DisplayList)
  File "mcedit2\util\glutils.py", line 137, in _compile (self is a DisplayList)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 117, in draw (self is a LoadableChunksRenderNode)
  File "mcedit2\rendering\loadablechunks.py", line 50, in drawSelf (self is a LoadableChunksRenderNode)
  File "mcedit2\rendering\loadablechunks.py", line 79, in createVertexArrays (self is a LoadableChunksNode)(named None)
  File "mceditlib\worldeditor.py", line 809, in chunkPositions (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 470, in chunkPositions (self is a WorldEditor)
  File "mceditlib\worldeditor.py", line 448, in preloadChunkPositions (self is a WorldEditor)
  File "mceditlib\anvil\worldfolder.py", line 219, in chunkPositions (self is a AnvilWorldFolder)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\student\\AppData\\Roaming\\.minecraft\\saves\\2\\region\\r.0.0.mca'

**Comment by DanPlayzJakov** [comment]
Same error.

**Comment by DanPlayzJakov** [comment]
Same error. I tried reinstalling MCedit. Nothing worked.

**Comment by tylersOH** [comment]
Literally the same, i wanted to edit my world to get rid of something but it won't even open it...

**Comment by FinnT730** [comment]
Maybe not have the world open at the same time?
If that also does not work, close Minecraft completely, and try again, if still nothing, please come back.
