### ISSUE TITLE
Can't Edit 1.13-1.14 World

### ISSUE THREAD

**Issue by beachguycasey31** [mcedit/mcedit2#502]
When I try to edit either a Minecraft 1.13 or 1.14 world is says it is loading world and only get up to 37% then crashes. I'm using MCEdit 2.0.0 Beta 14,  Windows 10 Home version 1903 (OS Build 18362.267).  Below is the error I'm getting when loading either a Minecraft 1.13 or 1.14 world. 
----------------------------------------------------------------------------------------------------------
An error occurred while opening C:\Users\casey\AppData\Roaming\.minecraft\saves\Modern Mansion Project 2
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)
----------------------------------------------------------------------------------------------------------

**Comment by DanPlayzJakov** [comment]
Try using the version of minecraft 1.11 and 1.8 1.9

**Comment by sbliven** [comment]
Duplicate of #420
