### ISSUE TITLE
"Key Blocks not found" error

### ISSUE THREAD

**Issue by alex4200** [mcedit/mcedit2#503]
Trying to open a new 1.14.3 map with `MCEdit 2.0.0-beta14` I get the following error; can this be fixed?

```

MCEdit version: 2.0.0-beta14
Python version: 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Platform: darwin
System version: Darwin-18.7.0-x86_64-i386-64bit
Processor: i386

Obtained a GL context with this format:
Valid: True
Version: 1.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 2.1 INTEL-12.10.12 (2, 1)
GL_VENDOR: 'Intel Inc.'
GL_RENDERER: 'Intel HD Graphics 5000 OpenGL Engine'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2/editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2/worldview/minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2/util/raycast.py", line 30, in rayCastInBounds  
  File "mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2/util/raycast.py", line 77, in rayCast  
  File "mcedit2/util/raycast.py", line 215, in advanceToChunk  
  File "mceditlib/worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib/worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib/cachefunc.py", line 77, in __call__  
  File "mceditlib/worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib/anvil/adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x124a20cf8>
```

**Comment by fightinggg** [comment]
me too
