### ISSUE TITLE
Wont let me do anything

### ISSUE THREAD

**Issue by dylandarko7** [mcedit/mcedit2#506]
Description of Issue:wont let me do anything from the menu

MCEdit Version:mac version

Minecraft Version the world was last opened in:Latest Snapshot

Operating System:MacOs

A screenshot or full text of the error from the console:MCEdit version: 2.0.0-beta14

Python version: 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Platform: darwin
System version: Darwin-18.7.0-x86_64-i386-64bit
Processor: i386

Obtained a GL context with this format:
Valid: True
Version: 1.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 2.1 INTEL-12.10.12 (2, 1)
GL_VENDOR: 'Intel Inc.'
GL_RENDERER: 'Intel(R) Iris(TM) Graphics 6100'

Unhandled Exception

Traceback (most recent call last):
File "mcedit2/editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
File "mcedit2/worldview/minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
File "mcedit2/util/raycast.py", line 30, in rayCastInBounds
File "mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
File "mcedit2/util/raycast.py", line 77, in rayCast
File "mcedit2/util/raycast.py", line 215, in advanceToChunk
File "mceditlib/worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
File "mceditlib/worldeditor.py", line 499, in getChunk (self is a WorldEditor)
File "mceditlib/cachefunc.py", line 77, in call
File "mceditlib/worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
File "mceditlib/anvil/adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x12cac92d8>
:

**Comment by AndreiSoupyCow** [comment]
Yea, I'm also having this issue.

**Comment by CZHO404** [comment]
This repo has not been update in over a year so im pretty sure that we cant use 1.14 worlds

**Comment by fightinggg** [comment]
me too
