### ISSUE TITLE
Crash when opening a server world. TypeError: Cannot cast.

### ISSUE THREAD

**Issue by jgilmore** [mcedit/mcedit2#509]
Situation: The thaumcraft mod has a bug, I'm trying to edit out the block causing a crash on server loading. See https://github.com/Azanor/thaumcraft-beta/issues/1513

But mcedit crashes too. However, no idea if it's related to the thaumcraft bug or....

casting dtype('float64') to dtype('int64') should totally be possible, it's just not allowed for some reason.

mcedit cloned from github today, couldn't get the beta sources to run.
forge-1.12.2-14.23.4.2705-universal
Ubuntu bionic

mods: 
ae2stuff-0.7.0.4-mc1.12.2.jar
AkashicTome-1.2-10.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
appliedenergistics2-rv5-stable-11.jar
astralsorcery-1.12.2-1.9.4.jar
AutoRegLib-1.3-20.jar
badwithernocookiereloaded-1.12.2-3.1.14.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
BloodMagic-1.12.2-2.3.3-101.jar
Botania+r1.10-362.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CookingForBlockheads_1.12.2-6.4.65.jar
CraftTweaker2-1.12-4.1.11.jar
CustomOreGen-1.12-1.8.1.jar
DummyCoreUnofficial-2.4.112.5.jar
EnderCore-1.12.2-0.5.41.jar
EnderIO-1.12.2-5.0.35.jar
extrautils2-1.12-1.9.4.jar
ExtremeReactors-1.12.2-0.4.5.49.jar
forestry_1.12.2-5.8.1.322.jar
furniture-5.13.0-1.12.2.jar
gravestone-1.10.1.jar
Guide-API-1.12-2.1.6-61.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.12.1.217.jar
LibEx-1.12.2-1.0.8.jar
MagicBees-1.12.2-3.1.10.jar
Mantle-1.12-1.3.2.24.jar
mcjtylib-1.12-3.0.5.jar
mystcraft-1.12.2-0.13.6.00.jar
mysticallib-1.12.2-1.3.7.jar
MysticWorld-1.12.2-1.4.4.jar
OptiFine_1.12.2_HD_U_E2.jar
Pam's+HarvestCraft+1.12.2zf.jar
Patchouli-1.0-20.jar
ProjectE-1.12-PE1.3.1B.jar
Psi-r1.1-62.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
roots-2-0.104.jar
Ruins-1.12.2.jar
Tainted-Magic-r7.82.jar
Thaumcraft-1.12.2-6.1.BETA25.jar
thaumicbases-3.2.265.4r-BBF.jar
ThaumicEquivalence-1.12.2-1.0.5.jar
ThaumicJEI-1.12.2-1.5.3-20.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
Treecapitator-1.12-at_0.9a.jar
twilightforest-1.12.2-3.8.689-universal.jar
WIT-1.12-1.0.24-43.jar
Xaeros_Minimap_1.18_Forge_1.12.jar
zerocore-1.12-0.1.2.2.jar

output: 
Running in portable mode. MCEdit-schematics and mcedit.ini are stored alongside MCEditData
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/jgilmore/src/ServerJarStorage named with the server's version number
Cached servers:  []
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
[   ERROR][pymclevel.infiniteworld.py:1311]:Error loading dimension DIM_MYST-2147483648: invalid literal for int() with base 10: '_MYST-2147483648'
[   ERROR][pymclevel.infiniteworld.py:1311]:Error loading dimension DIM_MYST-2147483648: invalid literal for int() with base 10: '_MYST-2147483648'
[   ERROR][                  root.py:1056]:MCEdit version 0.1.8build799-2-g8dcbd4f
Traceback (most recent call last):
  File "mcedit.py", line 1193, in <module>
    sys.exit(main(sys.argv))
  File "mcedit.py", line 1054, in main
    MCEdit.main()
  File "mcedit.py", line 975, in main
    rootwidget.run()
  File "/home/jgilmore/src/mcedit/albow/root.py", line 106, in run
    self.run_modal(None)
  File "/home/jgilmore/src/mcedit/albow/root.py", line 159, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "/home/jgilmore/src/mcedit/albow/widget.py", line 730, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/jgilmore/src/mcedit/albow/widget.py", line 730, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/jgilmore/src/mcedit/albow/widget.py", line 730, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/jgilmore/src/mcedit/albow/widget.py", line 730, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/jgilmore/src/mcedit/albow/widget.py", line 727, in gl_draw_all
    self.gl_draw_self(root, offset)
  File "/home/jgilmore/src/mcedit/albow/openglwidgets.py", line 23, in gl_draw_self
    self.gl_draw_viewport()
  File "/home/jgilmore/src/mcedit/albow/openglwidgets.py", line 28, in gl_draw_viewport
    self.setup_matrices()
  File "/home/jgilmore/src/mcedit/albow/openglwidgets.py", line 37, in setup_matrices
    self.setup_modelview()
  File "/home/jgilmore/src/mcedit/leveleditor.py", line 1248, in setup_modelview
    self.setModelview()
  File "/home/jgilmore/src/mcedit/leveleditor.py", line 407, in setModelview
    look += self.cameraVector
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

**Comment by jgilmore** [comment]
Also crashes using the windows version under wine.

[backtrace.txt](https://github.com/mcedit/mcedit2/files/3650137/backtrace.txt)

**Comment by Subjekt91** [comment]
Hey i want give an little heads-up the team moved on to an new editor named Amulet.
(such a stuff should really be written in the  readme.md) anyway they are now over there.
[https://github.com/Amulet-Team/Amulet-Map-Editor]()
