### ISSUE TITLE
cannot import name qt_loaders

### ISSUE THREAD

**Issue by ProfileFZY** [mcedit/mcedit2#523]
After installing all the requested dependencies, I got this:

`C:\SSD\AppPool\mcedit2>mcedit2
Traceback (most recent call last):
  File "D:\Program Files\compliers\Python27\Scripts\mcedit2-script.py", line 11, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\ssd\apppool\mcedit2\src\mcedit2\main.py", line 64, in <module>
    from qtconsole import qt_loaders
ImportError: cannot import name qt_loaders`

I've installed python-qt5 and qtconsole using pip; however, it proved to be useless ... What should I do next?

**Comment by ProfileFZY** [comment]
C:\SSD\AppPool\mcedit2>mcedit2
Traceback (most recent call last):
  File "D:\Program Files\compliers\Python27\Scripts\mcedit2-script.py", line 11, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "D:\Program Files\compliers\Python27\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\ssd\apppool\mcedit2\src\mcedit2\main.py", line 64, in <module>
    from qtconsole import qt_loaders
ImportError: cannot import name qt_loaders

**Comment by ProfileFZY** [comment]
**Problem solved.** I tried to modify the source code `File "c:\ssd\apppool\mcedit2\src\mcedit2\main.py", line 64, in <module>`, 
from 
```from qtconsole import qt_loaders``` 
to 
```from IPython.external import qt_loaders```
.

**Comment by PatrickMitchellUI** [comment]
> **Problem solved.** I tried to modify the source code `File "c:\ssd\apppool\mcedit2\src\mcedit2\main.py", line 64, in <module>`,

Worked for me, Please mark as solved
