### ISSUE TITLE
[1.15.2] <traceback object at 0x0000000026B40148>

### ISSUE THREAD

**Issue by Rudymil** [mcedit/mcedit2#530]
I get the following message when I open my world in version 1.15.2 :

```
MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 445.87 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 1060 3GB/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 486, in mouseMoveEvent (self is a CutawayWorldView)
  File "mcedit2\worldview\viewaction.py", line 221, in mouseMoveEvent (self is a TrackingMouseAction)
  File "mcedit2\editorsession.py", line 1365, in viewMouseMove (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1334, in updateStatusFromEvent (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1340, in updateStatus (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 1055, in getBlockID (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x0000000026B40148>
```

Does the 1.15.2 version is supported ?

**Comment by idevmans** [comment]
Hey buddy,unfortunately 1.15.2 not supported yet =(
Seems like 2.0 can`t read a 1.15.2 block look at last trace its says :
`AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x0000000026B40148>`
Tempory solution **Do map from 1.12.2 then open in 1.15.2**

**Comment by Rudymil** [comment]
Waiting for update...
