### ISSUE TITLE
MCEdit launch error

### ISSUE THREAD

**Issue by david09baz** [mcedit/mcedit2#531]
#### A screenshot or full text of the error from the console: 
An error occurred while opening C:\Users\SorryWontShareMyName\AppData\Roaming\.minecraft\saves\ooohh whatever
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by jakovmarkovanovic** [comment]
error too
Setting up console handler
Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>
  File "mcedit2\main.py", line 222, in main
  File "mcedit2\util\profiler.py", line 73, in _wrapper
  File "mcedit2\main.py", line 172, in startup
  File "mcedit2\sentry.py", line 15, in get_sentry_client
  File "site-packages\raven\base.py", line 177, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 8: ordinal not in range(128)
