### ISSUE TITLE
How to install/run MCEdit ?

### ISSUE THREAD

**Issue by MassiGaming** [mcedit/mcedit2#62]
Hi, I just downloaded MCEdit2 but when I run it it says it can't find something like an installed 1.8 version (or something like that) and another window apear where I can add something but I don't know what D:
So can anyone help me please ?
![how to install mcedit 2 0](https://cloud.githubusercontent.com/assets/12018006/7219330/95b89c26-e69a-11e4-8254-15f87f12ceb8.png)

-Thanks
MassiGaming :)

**Comment by codewarrior0** [comment]
Did you install Minecraft 1.8 using the official launcher?

**Comment by MassiGaming** [comment]
Yes.

**Comment by codewarrior0** [comment]
Click `Add`, then when the file browser comes up type in `%APPDATA%` and press return. This will take you to the folder that has `.minecraft` in it. Click on `.minecraft`, and then click the `Select Folder` button.

**Comment by codewarrior0** [comment]
This is a bug in build 226 and will be fixed in the next build.

**Comment by Ydamn62** [comment]
Well when i choose the minecraft folder this comes up....

An error has occured.

Unhandled exception:'MinecraftInstallsDialog' object has no attribute 'tableWidget'

**Comment by MassiGaming** [comment]
Yea same for me.

**Comment by Ydamn62** [comment]
Need help :P

**Comment by mikeblas** [comment]
after I pointed it at my Minecraft directory, it won't start at all. Here's the error I get:

```
C:\Users\mikeblas\Downloads\mcedit2-win64-2.0.0alpha-226>mcedit2.exe
Logging level set
sys.frozen is set
Logging to C:\Users\mikeblas\DOWNLO~1\MCEDIT~1.0AL\MCEdit User Data\mcedit.log
Setting up console handler
[WARNING][mcedit2.util.minecraftinstall:92]:Default install not usable: Minecraft folder does not exist.
[WARNING][mcedit2.editorapp:84]:UserFilesDirectory: C:\Users\mikeblas\DOWNLO~1\MCEDIT~1.0AL\MCEdit User Data
[ERROR][<string>:129]:Unhandled Exception:
        'MCEditApp' object has no attribute 'worldList'
Traceback (most recent call last):
  File "<string>", line 148, in <module>
  File "<string>", line 143, in main
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.util.profiler", line 63, in _wrapper (self is a Profiler)
  File "<string>", line 120, in startup
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.editorapp", line 241, in __init__ (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.worldlist", line 221, in __init__ (self is a WorldListWidget)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.worldlist", line 322, in reloadList (self is a WorldListWidget)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.worldlist", line 348, in showWorld (self is a WorldListWidget)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.editorapp", line 605, in getResourceLoaderForFilename (self is a MCEditApp)
AttributeError: 'MCEditApp' object has no attribute 'worldList'
```

**Comment by codewarrior0** [comment]
Fixed in build 232
