### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by soerenkk** [mcedit/mcedit2#70]
Hello.

I'm having trouble launching the application.

I suspect the reason is because I'm running Windows 8(.1), and is logging in using my Microsoft account. Since my first name contains an "ø" so does the username and userprofile on my Windows, and it seems MCEdit (all versions tested it with) cannot handle that and then terminates.

#### Notice some of the content is written in Danish (basically the path wasn't found, and I suspect the special character in my name/username/userprofile).

[INFO][mcedit2.util.settings:100]:Loading app settings from C:\Users\SREN~1\DOWNLO~1\MCEDIT~1.0AL\MCEdit User Data\mcedit2.ini
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:270]:Using accelerated ArrayDatatype
[INFO][mcedit2.util.profiler:85]:Decorating <function __iter__ at 0x000000000737D5F8> with ChunkUpdate
[INFO][mcedit2.util.profiler:85]:Decorating <function buildChunkMeshes at 0x000000000737D588> with buildChunkMeshes
[INFO][mcedit2.util.profiler:85]:Decorating <function buildSectionMeshes at 0x000000000737D6D8> with buildSectionMeshes
[INFO][mcedit2.util.profiler:85]:Decorating <function __iter__ at 0x0000000007381588> with SectionUpdate
[INFO][mcedit2.util.profiler:85]:Decorating <function work at 0x000000000738FAC8> with work
[INFO][mcedit2.util.profiler:85]:Decorating <function loadSections at 0x000000000759DE48> with SelectionScene
[INFO][mcedit2.util.profiler:85]:Decorating <function workOnChunk at 0x0000000007651828> with SlicedMesh
[INFO][mcedit2.util.minecraftinstall:205]:Checking install at C:\Users\Søren\AppData\Roaming\.minecraft
[INFO][mcedit2.util.minecraftinstall:212]:Found versions:
[u'1.8']
[INFO][mcedit2.util.minecraftinstall:205]:Checking install at C:\Users\Søren\AppData\Roaming\.minecraft
[INFO][mcedit2.util.minecraftinstall:212]:Found versions:
[u'1.8']
[WARNING][mcedit2.editorapp:84]:UserFilesDirectory: C:\Users\SREN~1\DOWNLO~1\MCEDIT~1.0AL\MCEdit User Data
[INFO][mcedit2.worldlist:116]:Size hint: PySide.QtCore.QSize(120, 54)
[INFO][mcedit2.worldlist:117]:Size : PySide.QtCore.QSize(120, 100)
[ERROR][<string>:129]:Unhandled Exception: 
	[Error 3] Den angivne sti blev ikke fundet: u'C:\\Users\\S\xf8ren\\AppData\\Roaming\\.minecraft\\resourcepacks\\*.*'
Traceback (most recent call last):
  File "<string>", line 148, in <module>  
  File "<string>", line 143, in main  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.util.profiler", line 63, in _wrapper (self is a Profiler)
  File "<string>", line 120, in startup  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.editorapp", line 241, in __init__ (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.worldlist", line 216, in __init__ (self is a WorldListWidget)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.worldlist", line 238, in _updateInstalls (self is a WorldListWidget)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.worldlist", line 253, in _updateVersionsAndResourcePacks (self is a WorldListWidget)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2.spec\out00-PYZ.pyz\mcedit2.util.minecraftinstall", line 226, in resourcePacks (self is a MCInstall)
WindowsError: [Error 3] Den angivne sti blev ikke fundet: u'C:\\Users\\S\xf8ren\\AppData\\Roaming\\.minecraft\\resourcepacks\\*.*'

**Comment by codewarrior0** [comment]
If it were the case that it isn't handling the "ø" in your name, it would have failed well before that point.

Can you check inside your `.minecraft` folder and tell me if there is a `resourcepacks` folder inside?

**Comment by soerenkk** [comment]
First of all it is the DireWolf20 1.7.10 pack provided by the FTB Launcher I'm trying to correct a possible corrupt map.

There is no ".minecraft" folder, there is however an "minecraft" folder, and yes that folder does have a "resourcepacks" folder, it is empty though.

**Comment by codewarrior0** [comment]
You do have vanilla Minecraft installed too, right? Can you check inside your `AppData\Roaming\.minecraft` folder for a `resourcepacks` folder? You can get there by running the game launcher, click "Edit Profile" and then click "Open Game Dir"

When you launched MCEdit the first time, did it ask you to set up any Minecraft installations?

**Comment by soerenkk** [comment]
I do have a vanilla Minecraft, however that folder do not have the "resourcepacks" folder inside.

No I opened the .exe file, and then it showed the cmd promt, wrote some lines and opened a message box with the error message with the text from the last line of the config file.

I've used the MCEdit tool before on this Windows install, a previous game got corrupted withing the last 6 months.

**Comment by codewarrior0** [comment]
This should be fixed in tonight's build.
